// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Int32 redScore;
            [FieldOffset(4)]
            public System.Int32 blueScore;
            [FieldOffset(8)]
            public System.Int32 robotMode;
            [FieldOffset(12)]
            public System.Single timeRemaining;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.redScoreMask;
            redScoreSimulationFrame = frame;
            FieldsMask |= _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.blueScoreMask;
            blueScoreSimulationFrame = frame;
            FieldsMask |= _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.robotModeMask;
            robotModeSimulationFrame = frame;
            FieldsMask |= _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.timeRemainingMask;
            timeRemainingSimulationFrame = frame;
        }

        public static unsafe _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 16) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 16) " +
                    "for component with ID 24");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 24");
            }

            var orig = new _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701();

            var comp = (Interop*)data;

            orig.redScore = comp->redScore;
            orig.blueScore = comp->blueScore;
            orig.robotMode = comp->robotMode;
            orig.timeRemaining = comp->timeRemaining;

            return orig;
        }


        public static uint redScoreMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame redScoreSimulationFrame;
        public System.Int32 redScore;
        public static uint blueScoreMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame blueScoreSimulationFrame;
        public System.Int32 blueScore;
        public static uint robotModeMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame robotModeSimulationFrame;
        public System.Int32 robotMode;
        public static uint timeRemainingMask => 0b00000000000000000000000000001000;
        public AbsoluteSimulationFrame timeRemainingSimulationFrame;
        public System.Single timeRemaining;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 24;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000001111;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 4;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;

        private static readonly System.Int32 _redScore_Min = -2147483648;
        private static readonly System.Int32 _redScore_Max = 2147483647;
        private static readonly System.Int32 _blueScore_Min = -2147483648;
        private static readonly System.Int32 _blueScore_Max = 2147483647;
        private static readonly System.Int32 _robotMode_Min = 0;
        private static readonly System.Int32 _robotMode_Max = 2;
        private static readonly float _timeRemaining_Min = -9223372036854775808f;
        private static readonly float _timeRemaining_Max = 9223372036854775807f;

        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.redScoreSimulationFrame = other.redScoreSimulationFrame;
                this.redScore = other.redScore;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.blueScoreSimulationFrame = other.blueScoreSimulationFrame;
                this.blueScore = other.blueScore;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.robotModeSimulationFrame = other.robotModeSimulationFrame;
                this.robotMode = other.robotMode;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.timeRemainingSimulationFrame = other.timeRemainingSimulationFrame;
                this.timeRemaining = other.timeRemaining;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 4);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.redScore, _redScore_Min, _redScore_Max, "_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.redScore", logger);
                data.redScore = Coherence.Utils.Bounds.Clamp(data.redScore, _redScore_Min, _redScore_Max);
                var fieldValue = data.redScore;
                bitStream.WriteIntegerRange(fieldValue, 32, -2147483648);
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.blueScore, _blueScore_Min, _blueScore_Max, "_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.blueScore", logger);
                data.blueScore = Coherence.Utils.Bounds.Clamp(data.blueScore, _blueScore_Min, _blueScore_Max);
                var fieldValue = data.blueScore;
                bitStream.WriteIntegerRange(fieldValue, 32, -2147483648);
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.robotMode, _robotMode_Min, _robotMode_Max, "_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.robotMode", logger);
                data.robotMode = Coherence.Utils.Bounds.Clamp(data.robotMode, _robotMode_Min, _robotMode_Max);
                var fieldValue = data.robotMode;
                bitStream.WriteIntegerRange(fieldValue, 2, 0);
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.timeRemaining, _timeRemaining_Min, _timeRemaining_Max, "_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.timeRemaining", logger);
                var fieldValue = data.timeRemaining;
                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }
            mask >>= 1;

            return mask;
        }

        public static _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(4);
            }

            var val = new _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701();
            if (bitStream.ReadMask())
            {

                val.redScore = bitStream.ReadIntegerRange(32, -2147483648);
                val.FieldsMask |= _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.redScoreMask;
            }
            if (bitStream.ReadMask())
            {

                val.blueScore = bitStream.ReadIntegerRange(32, -2147483648);
                val.FieldsMask |= _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.blueScoreMask;
            }
            if (bitStream.ReadMask())
            {

                val.robotMode = bitStream.ReadIntegerRange(2, 0);
                val.FieldsMask |= _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.robotModeMask;
            }
            if (bitStream.ReadMask())
            {

                val.timeRemaining = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.timeRemainingMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701(" +
                $" redScore: { this.redScore }" +
                $" blueScore: { this.blueScore }" +
                $" robotMode: { this.robotMode }" +
                $" timeRemaining: { this.timeRemaining }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(4, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(4, '0') })";
        }
    }

}
