// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using Coherence.Connection;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Int32 mode;
        }

        public static unsafe _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 4) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 4) " +
                    "for command with ID 7");
            }

            var orig = new _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb();
            var comp = (Interop*)data;
            orig.mode = comp->mode;
            return orig;
        }

        public System.Int32 mode;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Target { get; set; }
        public MessageTarget Routing { get; set; }
        public uint SenderParticipant { get; set; }
        public ClientID SenderClientID { get; set; }
        public long Frame { get; set; }
        public uint GetComponentType() => 7;
        public bool UsesMeta { get; set; }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb(
            Entity entity,
            System.Int32 mode
        )
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Target = default;
            Routing = MessageTarget.All;
            SenderParticipant = 0;
            SenderClientID = default;
            Frame = 0;
            UsesMeta = false;

            this.mode = mode; 
        }
        
        public static void Serialize(_a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteIntegerRange(commandData.mode, 2, 0);
        }
        
        public static _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var datamode = bitStream.ReadIntegerRange(2, 0);
    
            return new _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb()
            {
                Entity = entity,
                Routing = target,
                Target = target,
                mode = datamode
            };   
        }
    }

}
