// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using Coherence.Connection;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using System;
    using UnityEngine;

    public struct _dc51daba6bd26400abb19c32e4b4b945 : IEntityInput, IEquatable<_dc51daba6bd26400abb19c32e4b4b945>
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Single j0a0;
            [FieldOffset(4)]
            public System.Single j0a1;
            [FieldOffset(8)]
            public System.Single j0a2;
            [FieldOffset(12)]
            public System.Single j0a3;
            [FieldOffset(16)]
            public System.Single j0a4;
            [FieldOffset(20)]
            public System.Single j0a5;
            [FieldOffset(24)]
            public System.Single j1a0;
            [FieldOffset(28)]
            public System.Single j1a1;
            [FieldOffset(32)]
            public System.Single j1a2;
            [FieldOffset(36)]
            public System.Single j1a3;
            [FieldOffset(40)]
            public System.Single j1a4;
            [FieldOffset(44)]
            public System.Single j1a5;
            [FieldOffset(48)]
            public System.Single j2a0;
            [FieldOffset(52)]
            public System.Single j2a1;
            [FieldOffset(56)]
            public System.Single j2a2;
            [FieldOffset(60)]
            public System.Single j2a3;
            [FieldOffset(64)]
            public System.Single j2a4;
            [FieldOffset(68)]
            public System.Single j2a5;
            [FieldOffset(72)]
            public System.Single j3a0;
            [FieldOffset(76)]
            public System.Single j3a1;
            [FieldOffset(80)]
            public System.Single j3a2;
            [FieldOffset(84)]
            public System.Single j3a3;
            [FieldOffset(88)]
            public System.Single j3a4;
            [FieldOffset(92)]
            public System.Single j3a5;
            [FieldOffset(96)]
            public System.Byte j0b0;
            [FieldOffset(97)]
            public System.Byte j0b1;
            [FieldOffset(98)]
            public System.Byte j0b2;
            [FieldOffset(99)]
            public System.Byte j0b3;
            [FieldOffset(100)]
            public System.Byte j0b4;
            [FieldOffset(101)]
            public System.Byte j0b5;
            [FieldOffset(102)]
            public System.Byte j0b6;
            [FieldOffset(103)]
            public System.Byte j0b7;
            [FieldOffset(104)]
            public System.Byte j0b8;
            [FieldOffset(105)]
            public System.Byte j0b9;
            [FieldOffset(106)]
            public System.Byte j0b10;
            [FieldOffset(107)]
            public System.Byte j0b11;
            [FieldOffset(108)]
            public System.Byte j1b0;
            [FieldOffset(109)]
            public System.Byte j1b1;
            [FieldOffset(110)]
            public System.Byte j1b2;
            [FieldOffset(111)]
            public System.Byte j1b3;
            [FieldOffset(112)]
            public System.Byte j1b4;
            [FieldOffset(113)]
            public System.Byte j1b5;
            [FieldOffset(114)]
            public System.Byte j1b6;
            [FieldOffset(115)]
            public System.Byte j1b7;
            [FieldOffset(116)]
            public System.Byte j1b8;
            [FieldOffset(117)]
            public System.Byte j1b9;
            [FieldOffset(118)]
            public System.Byte j1b10;
            [FieldOffset(119)]
            public System.Byte j1b11;
            [FieldOffset(120)]
            public System.Byte j2b0;
            [FieldOffset(121)]
            public System.Byte j2b1;
            [FieldOffset(122)]
            public System.Byte j2b2;
            [FieldOffset(123)]
            public System.Byte j2b3;
            [FieldOffset(124)]
            public System.Byte j2b4;
            [FieldOffset(125)]
            public System.Byte j2b5;
            [FieldOffset(126)]
            public System.Byte j2b6;
            [FieldOffset(127)]
            public System.Byte j2b7;
            [FieldOffset(128)]
            public System.Byte j2b8;
            [FieldOffset(129)]
            public System.Byte j2b9;
            [FieldOffset(130)]
            public System.Byte j2b10;
            [FieldOffset(131)]
            public System.Byte j2b11;
            [FieldOffset(132)]
            public System.Byte j3b0;
            [FieldOffset(133)]
            public System.Byte j3b1;
            [FieldOffset(134)]
            public System.Byte j3b2;
            [FieldOffset(135)]
            public System.Byte j3b3;
            [FieldOffset(136)]
            public System.Byte j3b4;
            [FieldOffset(137)]
            public System.Byte j3b5;
            [FieldOffset(138)]
            public System.Byte j3b6;
            [FieldOffset(139)]
            public System.Byte j3b7;
            [FieldOffset(140)]
            public System.Byte j3b8;
            [FieldOffset(141)]
            public System.Byte j3b9;
            [FieldOffset(142)]
            public System.Byte j3b10;
            [FieldOffset(143)]
            public System.Byte j3b11;
        }

        public static unsafe _dc51daba6bd26400abb19c32e4b4b945 FromInterop(System.IntPtr data, System.Int32 dataSize)
        {
            if (dataSize != 144) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 144) " +
                    "for input with ID 1");
            }

            var orig = new _dc51daba6bd26400abb19c32e4b4b945();
            var comp = (Interop*)data;
            orig.j0a0 = comp->j0a0;
            orig.j0a1 = comp->j0a1;
            orig.j0a2 = comp->j0a2;
            orig.j0a3 = comp->j0a3;
            orig.j0a4 = comp->j0a4;
            orig.j0a5 = comp->j0a5;
            orig.j1a0 = comp->j1a0;
            orig.j1a1 = comp->j1a1;
            orig.j1a2 = comp->j1a2;
            orig.j1a3 = comp->j1a3;
            orig.j1a4 = comp->j1a4;
            orig.j1a5 = comp->j1a5;
            orig.j2a0 = comp->j2a0;
            orig.j2a1 = comp->j2a1;
            orig.j2a2 = comp->j2a2;
            orig.j2a3 = comp->j2a3;
            orig.j2a4 = comp->j2a4;
            orig.j2a5 = comp->j2a5;
            orig.j3a0 = comp->j3a0;
            orig.j3a1 = comp->j3a1;
            orig.j3a2 = comp->j3a2;
            orig.j3a3 = comp->j3a3;
            orig.j3a4 = comp->j3a4;
            orig.j3a5 = comp->j3a5;
            orig.j0b0 = comp->j0b0 != 0;
            orig.j0b1 = comp->j0b1 != 0;
            orig.j0b2 = comp->j0b2 != 0;
            orig.j0b3 = comp->j0b3 != 0;
            orig.j0b4 = comp->j0b4 != 0;
            orig.j0b5 = comp->j0b5 != 0;
            orig.j0b6 = comp->j0b6 != 0;
            orig.j0b7 = comp->j0b7 != 0;
            orig.j0b8 = comp->j0b8 != 0;
            orig.j0b9 = comp->j0b9 != 0;
            orig.j0b10 = comp->j0b10 != 0;
            orig.j0b11 = comp->j0b11 != 0;
            orig.j1b0 = comp->j1b0 != 0;
            orig.j1b1 = comp->j1b1 != 0;
            orig.j1b2 = comp->j1b2 != 0;
            orig.j1b3 = comp->j1b3 != 0;
            orig.j1b4 = comp->j1b4 != 0;
            orig.j1b5 = comp->j1b5 != 0;
            orig.j1b6 = comp->j1b6 != 0;
            orig.j1b7 = comp->j1b7 != 0;
            orig.j1b8 = comp->j1b8 != 0;
            orig.j1b9 = comp->j1b9 != 0;
            orig.j1b10 = comp->j1b10 != 0;
            orig.j1b11 = comp->j1b11 != 0;
            orig.j2b0 = comp->j2b0 != 0;
            orig.j2b1 = comp->j2b1 != 0;
            orig.j2b2 = comp->j2b2 != 0;
            orig.j2b3 = comp->j2b3 != 0;
            orig.j2b4 = comp->j2b4 != 0;
            orig.j2b5 = comp->j2b5 != 0;
            orig.j2b6 = comp->j2b6 != 0;
            orig.j2b7 = comp->j2b7 != 0;
            orig.j2b8 = comp->j2b8 != 0;
            orig.j2b9 = comp->j2b9 != 0;
            orig.j2b10 = comp->j2b10 != 0;
            orig.j2b11 = comp->j2b11 != 0;
            orig.j3b0 = comp->j3b0 != 0;
            orig.j3b1 = comp->j3b1 != 0;
            orig.j3b2 = comp->j3b2 != 0;
            orig.j3b3 = comp->j3b3 != 0;
            orig.j3b4 = comp->j3b4 != 0;
            orig.j3b5 = comp->j3b5 != 0;
            orig.j3b6 = comp->j3b6 != 0;
            orig.j3b7 = comp->j3b7 != 0;
            orig.j3b8 = comp->j3b8 != 0;
            orig.j3b9 = comp->j3b9 != 0;
            orig.j3b10 = comp->j3b10 != 0;
            orig.j3b11 = comp->j3b11 != 0;
            return orig;
        }

        public uint GetComponentType() => 1;

        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint SenderParticipant { get; set; }
        public ClientID SenderClientID { get; set; }
        public long Frame { get; set; }
        private bool isRemoteInput;

        public System.Single j0a0;
        public System.Single j0a1;
        public System.Single j0a2;
        public System.Single j0a3;
        public System.Single j0a4;
        public System.Single j0a5;
        public System.Single j1a0;
        public System.Single j1a1;
        public System.Single j1a2;
        public System.Single j1a3;
        public System.Single j1a4;
        public System.Single j1a5;
        public System.Single j2a0;
        public System.Single j2a1;
        public System.Single j2a2;
        public System.Single j2a3;
        public System.Single j2a4;
        public System.Single j2a5;
        public System.Single j3a0;
        public System.Single j3a1;
        public System.Single j3a2;
        public System.Single j3a3;
        public System.Single j3a4;
        public System.Single j3a5;
        public System.Boolean j0b0;
        public System.Boolean j0b1;
        public System.Boolean j0b2;
        public System.Boolean j0b3;
        public System.Boolean j0b4;
        public System.Boolean j0b5;
        public System.Boolean j0b6;
        public System.Boolean j0b7;
        public System.Boolean j0b8;
        public System.Boolean j0b9;
        public System.Boolean j0b10;
        public System.Boolean j0b11;
        public System.Boolean j1b0;
        public System.Boolean j1b1;
        public System.Boolean j1b2;
        public System.Boolean j1b3;
        public System.Boolean j1b4;
        public System.Boolean j1b5;
        public System.Boolean j1b6;
        public System.Boolean j1b7;
        public System.Boolean j1b8;
        public System.Boolean j1b9;
        public System.Boolean j1b10;
        public System.Boolean j1b11;
        public System.Boolean j2b0;
        public System.Boolean j2b1;
        public System.Boolean j2b2;
        public System.Boolean j2b3;
        public System.Boolean j2b4;
        public System.Boolean j2b5;
        public System.Boolean j2b6;
        public System.Boolean j2b7;
        public System.Boolean j2b8;
        public System.Boolean j2b9;
        public System.Boolean j2b10;
        public System.Boolean j2b11;
        public System.Boolean j3b0;
        public System.Boolean j3b1;
        public System.Boolean j3b2;
        public System.Boolean j3b3;
        public System.Boolean j3b4;
        public System.Boolean j3b5;
        public System.Boolean j3b6;
        public System.Boolean j3b7;
        public System.Boolean j3b8;
        public System.Boolean j3b9;
        public System.Boolean j3b10;
        public System.Boolean j3b11;

        public _dc51daba6bd26400abb19c32e4b4b945(
        Entity entity,
        long frame,
        System.Single j0a0,
        System.Single j0a1,
        System.Single j0a2,
        System.Single j0a3,
        System.Single j0a4,
        System.Single j0a5,
        System.Single j1a0,
        System.Single j1a1,
        System.Single j1a2,
        System.Single j1a3,
        System.Single j1a4,
        System.Single j1a5,
        System.Single j2a0,
        System.Single j2a1,
        System.Single j2a2,
        System.Single j2a3,
        System.Single j2a4,
        System.Single j2a5,
        System.Single j3a0,
        System.Single j3a1,
        System.Single j3a2,
        System.Single j3a3,
        System.Single j3a4,
        System.Single j3a5,
        System.Boolean j0b0,
        System.Boolean j0b1,
        System.Boolean j0b2,
        System.Boolean j0b3,
        System.Boolean j0b4,
        System.Boolean j0b5,
        System.Boolean j0b6,
        System.Boolean j0b7,
        System.Boolean j0b8,
        System.Boolean j0b9,
        System.Boolean j0b10,
        System.Boolean j0b11,
        System.Boolean j1b0,
        System.Boolean j1b1,
        System.Boolean j1b2,
        System.Boolean j1b3,
        System.Boolean j1b4,
        System.Boolean j1b5,
        System.Boolean j1b6,
        System.Boolean j1b7,
        System.Boolean j1b8,
        System.Boolean j1b9,
        System.Boolean j1b10,
        System.Boolean j1b11,
        System.Boolean j2b0,
        System.Boolean j2b1,
        System.Boolean j2b2,
        System.Boolean j2b3,
        System.Boolean j2b4,
        System.Boolean j2b5,
        System.Boolean j2b6,
        System.Boolean j2b7,
        System.Boolean j2b8,
        System.Boolean j2b9,
        System.Boolean j2b10,
        System.Boolean j2b11,
        System.Boolean j3b0,
        System.Boolean j3b1,
        System.Boolean j3b2,
        System.Boolean j3b3,
        System.Boolean j3b4,
        System.Boolean j3b5,
        System.Boolean j3b6,
        System.Boolean j3b7,
        System.Boolean j3b8,
        System.Boolean j3b9,
        System.Boolean j3b10,
        System.Boolean j3b11,
        bool isRemoteInput)
        {
            this.Entity = entity;
            this.ChannelID = Coherence.ChannelID.Default;
            this.Routing = MessageTarget.All;
            this.SenderParticipant = 0;
            this.SenderClientID = default;
            this.Frame = frame;
            this.isRemoteInput = isRemoteInput;
            this.j0a0 = j0a0;
            this.j0a1 = j0a1;
            this.j0a2 = j0a2;
            this.j0a3 = j0a3;
            this.j0a4 = j0a4;
            this.j0a5 = j0a5;
            this.j1a0 = j1a0;
            this.j1a1 = j1a1;
            this.j1a2 = j1a2;
            this.j1a3 = j1a3;
            this.j1a4 = j1a4;
            this.j1a5 = j1a5;
            this.j2a0 = j2a0;
            this.j2a1 = j2a1;
            this.j2a2 = j2a2;
            this.j2a3 = j2a3;
            this.j2a4 = j2a4;
            this.j2a5 = j2a5;
            this.j3a0 = j3a0;
            this.j3a1 = j3a1;
            this.j3a2 = j3a2;
            this.j3a3 = j3a3;
            this.j3a4 = j3a4;
            this.j3a5 = j3a5;
            this.j0b0 = j0b0;
            this.j0b1 = j0b1;
            this.j0b2 = j0b2;
            this.j0b3 = j0b3;
            this.j0b4 = j0b4;
            this.j0b5 = j0b5;
            this.j0b6 = j0b6;
            this.j0b7 = j0b7;
            this.j0b8 = j0b8;
            this.j0b9 = j0b9;
            this.j0b10 = j0b10;
            this.j0b11 = j0b11;
            this.j1b0 = j1b0;
            this.j1b1 = j1b1;
            this.j1b2 = j1b2;
            this.j1b3 = j1b3;
            this.j1b4 = j1b4;
            this.j1b5 = j1b5;
            this.j1b6 = j1b6;
            this.j1b7 = j1b7;
            this.j1b8 = j1b8;
            this.j1b9 = j1b9;
            this.j1b10 = j1b10;
            this.j1b11 = j1b11;
            this.j2b0 = j2b0;
            this.j2b1 = j2b1;
            this.j2b2 = j2b2;
            this.j2b3 = j2b3;
            this.j2b4 = j2b4;
            this.j2b5 = j2b5;
            this.j2b6 = j2b6;
            this.j2b7 = j2b7;
            this.j2b8 = j2b8;
            this.j2b9 = j2b9;
            this.j2b10 = j2b10;
            this.j2b11 = j2b11;
            this.j3b0 = j3b0;
            this.j3b1 = j3b1;
            this.j3b2 = j3b2;
            this.j3b3 = j3b3;
            this.j3b4 = j3b4;
            this.j3b5 = j3b5;
            this.j3b6 = j3b6;
            this.j3b7 = j3b7;
            this.j3b8 = j3b8;
            this.j3b9 = j3b9;
            this.j3b10 = j3b10;
            this.j3b11 = j3b11;
        }

        public override string ToString()
        {
            return $"Entity: {Entity}, Frame: {Frame}, Inputs: [j0a0:{j0a0}, j0a1:{j0a1}, j0a2:{j0a2}, j0a3:{j0a3}, j0a4:{j0a4}, j0a5:{j0a5}, j1a0:{j1a0}, j1a1:{j1a1}, j1a2:{j1a2}, j1a3:{j1a3}, j1a4:{j1a4}, j1a5:{j1a5}, j2a0:{j2a0}, j2a1:{j2a1}, j2a2:{j2a2}, j2a3:{j2a3}, j2a4:{j2a4}, j2a5:{j2a5}, j3a0:{j3a0}, j3a1:{j3a1}, j3a2:{j3a2}, j3a3:{j3a3}, j3a4:{j3a4}, j3a5:{j3a5}, j0b0:{j0b0}, j0b1:{j0b1}, j0b2:{j0b2}, j0b3:{j0b3}, j0b4:{j0b4}, j0b5:{j0b5}, j0b6:{j0b6}, j0b7:{j0b7}, j0b8:{j0b8}, j0b9:{j0b9}, j0b10:{j0b10}, j0b11:{j0b11}, j1b0:{j1b0}, j1b1:{j1b1}, j1b2:{j1b2}, j1b3:{j1b3}, j1b4:{j1b4}, j1b5:{j1b5}, j1b6:{j1b6}, j1b7:{j1b7}, j1b8:{j1b8}, j1b9:{j1b9}, j1b10:{j1b10}, j1b11:{j1b11}, j2b0:{j2b0}, j2b1:{j2b1}, j2b2:{j2b2}, j2b3:{j2b3}, j2b4:{j2b4}, j2b5:{j2b5}, j2b6:{j2b6}, j2b7:{j2b7}, j2b8:{j2b8}, j2b9:{j2b9}, j2b10:{j2b10}, j2b11:{j2b11}, j3b0:{j3b0}, j3b1:{j3b1}, j3b2:{j3b2}, j3b3:{j3b3}, j3b4:{j3b4}, j3b5:{j3b5}, j3b6:{j3b6}, j3b7:{j3b7}, j3b8:{j3b8}, j3b9:{j3b9}, j3b10:{j3b10}, j3b11:{j3b11}]";
        }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }

        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() => default;

        public void NullEntityRefs(Entity entity) { }

        public bool Equals(_dc51daba6bd26400abb19c32e4b4b945 other)
        {
            return
                this.j0a0 == other.j0a0&&
                this.j0a1 == other.j0a1&&
                this.j0a2 == other.j0a2&&
                this.j0a3 == other.j0a3&&
                this.j0a4 == other.j0a4&&
                this.j0a5 == other.j0a5&&
                this.j1a0 == other.j1a0&&
                this.j1a1 == other.j1a1&&
                this.j1a2 == other.j1a2&&
                this.j1a3 == other.j1a3&&
                this.j1a4 == other.j1a4&&
                this.j1a5 == other.j1a5&&
                this.j2a0 == other.j2a0&&
                this.j2a1 == other.j2a1&&
                this.j2a2 == other.j2a2&&
                this.j2a3 == other.j2a3&&
                this.j2a4 == other.j2a4&&
                this.j2a5 == other.j2a5&&
                this.j3a0 == other.j3a0&&
                this.j3a1 == other.j3a1&&
                this.j3a2 == other.j3a2&&
                this.j3a3 == other.j3a3&&
                this.j3a4 == other.j3a4&&
                this.j3a5 == other.j3a5&&
                this.j0b0 == other.j0b0&&
                this.j0b1 == other.j0b1&&
                this.j0b2 == other.j0b2&&
                this.j0b3 == other.j0b3&&
                this.j0b4 == other.j0b4&&
                this.j0b5 == other.j0b5&&
                this.j0b6 == other.j0b6&&
                this.j0b7 == other.j0b7&&
                this.j0b8 == other.j0b8&&
                this.j0b9 == other.j0b9&&
                this.j0b10 == other.j0b10&&
                this.j0b11 == other.j0b11&&
                this.j1b0 == other.j1b0&&
                this.j1b1 == other.j1b1&&
                this.j1b2 == other.j1b2&&
                this.j1b3 == other.j1b3&&
                this.j1b4 == other.j1b4&&
                this.j1b5 == other.j1b5&&
                this.j1b6 == other.j1b6&&
                this.j1b7 == other.j1b7&&
                this.j1b8 == other.j1b8&&
                this.j1b9 == other.j1b9&&
                this.j1b10 == other.j1b10&&
                this.j1b11 == other.j1b11&&
                this.j2b0 == other.j2b0&&
                this.j2b1 == other.j2b1&&
                this.j2b2 == other.j2b2&&
                this.j2b3 == other.j2b3&&
                this.j2b4 == other.j2b4&&
                this.j2b5 == other.j2b5&&
                this.j2b6 == other.j2b6&&
                this.j2b7 == other.j2b7&&
                this.j2b8 == other.j2b8&&
                this.j2b9 == other.j2b9&&
                this.j2b10 == other.j2b10&&
                this.j2b11 == other.j2b11&&
                this.j3b0 == other.j3b0&&
                this.j3b1 == other.j3b1&&
                this.j3b2 == other.j3b2&&
                this.j3b3 == other.j3b3&&
                this.j3b4 == other.j3b4&&
                this.j3b5 == other.j3b5&&
                this.j3b6 == other.j3b6&&
                this.j3b7 == other.j3b7&&
                this.j3b8 == other.j3b8&&
                this.j3b9 == other.j3b9&&
                this.j3b10 == other.j3b10&&
                this.j3b11 == other.j3b11;
        }

        public static void Serialize(_dc51daba6bd26400abb19c32e4b4b945 inputData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteFloat(inputData.j0a0, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j0a1, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j0a2, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j0a3, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j0a4, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j0a5, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j1a0, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j1a1, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j1a2, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j1a3, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j1a4, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j1a5, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j2a0, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j2a1, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j2a2, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j2a3, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j2a4, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j2a5, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j3a0, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j3a1, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j3a2, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j3a3, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j3a4, FloatMeta.NoCompression());
            bitStream.WriteFloat(inputData.j3a5, FloatMeta.NoCompression());
            bitStream.WriteBool(inputData.j0b0);
            bitStream.WriteBool(inputData.j0b1);
            bitStream.WriteBool(inputData.j0b2);
            bitStream.WriteBool(inputData.j0b3);
            bitStream.WriteBool(inputData.j0b4);
            bitStream.WriteBool(inputData.j0b5);
            bitStream.WriteBool(inputData.j0b6);
            bitStream.WriteBool(inputData.j0b7);
            bitStream.WriteBool(inputData.j0b8);
            bitStream.WriteBool(inputData.j0b9);
            bitStream.WriteBool(inputData.j0b10);
            bitStream.WriteBool(inputData.j0b11);
            bitStream.WriteBool(inputData.j1b0);
            bitStream.WriteBool(inputData.j1b1);
            bitStream.WriteBool(inputData.j1b2);
            bitStream.WriteBool(inputData.j1b3);
            bitStream.WriteBool(inputData.j1b4);
            bitStream.WriteBool(inputData.j1b5);
            bitStream.WriteBool(inputData.j1b6);
            bitStream.WriteBool(inputData.j1b7);
            bitStream.WriteBool(inputData.j1b8);
            bitStream.WriteBool(inputData.j1b9);
            bitStream.WriteBool(inputData.j1b10);
            bitStream.WriteBool(inputData.j1b11);
            bitStream.WriteBool(inputData.j2b0);
            bitStream.WriteBool(inputData.j2b1);
            bitStream.WriteBool(inputData.j2b2);
            bitStream.WriteBool(inputData.j2b3);
            bitStream.WriteBool(inputData.j2b4);
            bitStream.WriteBool(inputData.j2b5);
            bitStream.WriteBool(inputData.j2b6);
            bitStream.WriteBool(inputData.j2b7);
            bitStream.WriteBool(inputData.j2b8);
            bitStream.WriteBool(inputData.j2b9);
            bitStream.WriteBool(inputData.j2b10);
            bitStream.WriteBool(inputData.j2b11);
            bitStream.WriteBool(inputData.j3b0);
            bitStream.WriteBool(inputData.j3b1);
            bitStream.WriteBool(inputData.j3b2);
            bitStream.WriteBool(inputData.j3b3);
            bitStream.WriteBool(inputData.j3b4);
            bitStream.WriteBool(inputData.j3b5);
            bitStream.WriteBool(inputData.j3b6);
            bitStream.WriteBool(inputData.j3b7);
            bitStream.WriteBool(inputData.j3b8);
            bitStream.WriteBool(inputData.j3b9);
            bitStream.WriteBool(inputData.j3b10);
            bitStream.WriteBool(inputData.j3b11);
        }

        public static _dc51daba6bd26400abb19c32e4b4b945 Deserialize(IInProtocolBitStream bitStream, Entity entity, long frame)
        {
            var dataj0a0 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj0a1 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj0a2 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj0a3 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj0a4 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj0a5 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj1a0 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj1a1 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj1a2 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj1a3 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj1a4 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj1a5 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj2a0 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj2a1 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj2a2 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj2a3 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj2a4 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj2a5 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj3a0 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj3a1 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj3a2 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj3a3 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj3a4 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj3a5 = bitStream.ReadFloat(FloatMeta.NoCompression());
            var dataj0b0 = bitStream.ReadBool();
            var dataj0b1 = bitStream.ReadBool();
            var dataj0b2 = bitStream.ReadBool();
            var dataj0b3 = bitStream.ReadBool();
            var dataj0b4 = bitStream.ReadBool();
            var dataj0b5 = bitStream.ReadBool();
            var dataj0b6 = bitStream.ReadBool();
            var dataj0b7 = bitStream.ReadBool();
            var dataj0b8 = bitStream.ReadBool();
            var dataj0b9 = bitStream.ReadBool();
            var dataj0b10 = bitStream.ReadBool();
            var dataj0b11 = bitStream.ReadBool();
            var dataj1b0 = bitStream.ReadBool();
            var dataj1b1 = bitStream.ReadBool();
            var dataj1b2 = bitStream.ReadBool();
            var dataj1b3 = bitStream.ReadBool();
            var dataj1b4 = bitStream.ReadBool();
            var dataj1b5 = bitStream.ReadBool();
            var dataj1b6 = bitStream.ReadBool();
            var dataj1b7 = bitStream.ReadBool();
            var dataj1b8 = bitStream.ReadBool();
            var dataj1b9 = bitStream.ReadBool();
            var dataj1b10 = bitStream.ReadBool();
            var dataj1b11 = bitStream.ReadBool();
            var dataj2b0 = bitStream.ReadBool();
            var dataj2b1 = bitStream.ReadBool();
            var dataj2b2 = bitStream.ReadBool();
            var dataj2b3 = bitStream.ReadBool();
            var dataj2b4 = bitStream.ReadBool();
            var dataj2b5 = bitStream.ReadBool();
            var dataj2b6 = bitStream.ReadBool();
            var dataj2b7 = bitStream.ReadBool();
            var dataj2b8 = bitStream.ReadBool();
            var dataj2b9 = bitStream.ReadBool();
            var dataj2b10 = bitStream.ReadBool();
            var dataj2b11 = bitStream.ReadBool();
            var dataj3b0 = bitStream.ReadBool();
            var dataj3b1 = bitStream.ReadBool();
            var dataj3b2 = bitStream.ReadBool();
            var dataj3b3 = bitStream.ReadBool();
            var dataj3b4 = bitStream.ReadBool();
            var dataj3b5 = bitStream.ReadBool();
            var dataj3b6 = bitStream.ReadBool();
            var dataj3b7 = bitStream.ReadBool();
            var dataj3b8 = bitStream.ReadBool();
            var dataj3b9 = bitStream.ReadBool();
            var dataj3b10 = bitStream.ReadBool();
            var dataj3b11 = bitStream.ReadBool();

            return new _dc51daba6bd26400abb19c32e4b4b945()
            {
                Entity = entity,
                Frame = frame,
                j0a0 = dataj0a0,
                j0a1 = dataj0a1,
                j0a2 = dataj0a2,
                j0a3 = dataj0a3,
                j0a4 = dataj0a4,
                j0a5 = dataj0a5,
                j1a0 = dataj1a0,
                j1a1 = dataj1a1,
                j1a2 = dataj1a2,
                j1a3 = dataj1a3,
                j1a4 = dataj1a4,
                j1a5 = dataj1a5,
                j2a0 = dataj2a0,
                j2a1 = dataj2a1,
                j2a2 = dataj2a2,
                j2a3 = dataj2a3,
                j2a4 = dataj2a4,
                j2a5 = dataj2a5,
                j3a0 = dataj3a0,
                j3a1 = dataj3a1,
                j3a2 = dataj3a2,
                j3a3 = dataj3a3,
                j3a4 = dataj3a4,
                j3a5 = dataj3a5,
                j0b0 = dataj0b0,
                j0b1 = dataj0b1,
                j0b2 = dataj0b2,
                j0b3 = dataj0b3,
                j0b4 = dataj0b4,
                j0b5 = dataj0b5,
                j0b6 = dataj0b6,
                j0b7 = dataj0b7,
                j0b8 = dataj0b8,
                j0b9 = dataj0b9,
                j0b10 = dataj0b10,
                j0b11 = dataj0b11,
                j1b0 = dataj1b0,
                j1b1 = dataj1b1,
                j1b2 = dataj1b2,
                j1b3 = dataj1b3,
                j1b4 = dataj1b4,
                j1b5 = dataj1b5,
                j1b6 = dataj1b6,
                j1b7 = dataj1b7,
                j1b8 = dataj1b8,
                j1b9 = dataj1b9,
                j1b10 = dataj1b10,
                j1b11 = dataj1b11,
                j2b0 = dataj2b0,
                j2b1 = dataj2b1,
                j2b2 = dataj2b2,
                j2b3 = dataj2b3,
                j2b4 = dataj2b4,
                j2b5 = dataj2b5,
                j2b6 = dataj2b6,
                j2b7 = dataj2b7,
                j2b8 = dataj2b8,
                j2b9 = dataj2b9,
                j2b10 = dataj2b10,
                j2b11 = dataj2b11,
                j3b0 = dataj3b0,
                j3b1 = dataj3b1,
                j3b2 = dataj3b2,
                j3b3 = dataj3b3,
                j3b4 = dataj3b4,
                j3b5 = dataj3b5,
                j3b6 = dataj3b6,
                j3b7 = dataj3b7,
                j3b8 = dataj3b8,
                j3b9 = dataj3b9,
                j3b10 = dataj3b10,
                j3b11 = dataj3b11,
                isRemoteInput = true
            };
        }
    }

}
