// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using Coherence.Connection;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public ByteArray privateKeyChallenge;
        }

        public static unsafe _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 16) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 16) " +
                    "for command with ID 8");
            }

            var orig = new _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b();
            var comp = (Interop*)data;
            orig.privateKeyChallenge = comp->privateKeyChallenge.Data != null ? System.Text.Encoding.UTF8.GetString((byte*)comp->privateKeyChallenge.Data, (int)comp->privateKeyChallenge.Length) : null;
            return orig;
        }

        public System.String privateKeyChallenge;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Target { get; set; }
        public MessageTarget Routing { get; set; }
        public uint SenderParticipant { get; set; }
        public ClientID SenderClientID { get; set; }
        public long Frame { get; set; }
        public uint GetComponentType() => 8;
        public bool UsesMeta { get; set; }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b(
            Entity entity,
            System.String privateKeyChallenge
        )
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Target = default;
            Routing = MessageTarget.All;
            SenderParticipant = 0;
            SenderClientID = default;
            Frame = 0;
            UsesMeta = false;

            this.privateKeyChallenge = privateKeyChallenge; 
        }
        
        public static void Serialize(_dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteShortString(commandData.privateKeyChallenge);
        }
        
        public static _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataprivateKeyChallenge = bitStream.ReadShortString();
    
            return new _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b()
            {
                Entity = entity,
                Routing = target,
                Target = target,
                privateKeyChallenge = dataprivateKeyChallenge
            };   
        }
    }

}
