// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Text;
    using Coherence;
    using Coherence.Brisk;
    using Coherence.ProtocolDef;
    using Coherence.Connection;
    using Coherence.Entities;
    using System.Collections.Generic;
    using Coherence.SimulationFrame;
    using Coherence.Core;

    public class DataInteropHandler : IDataInteropHandler
    {
        public unsafe ICoherenceComponentData GetComponent(UInt32 type, IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            switch(type)
            {
                case 0: return WorldPosition.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 1: return WorldOrientation.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 2: return LocalUserComponent.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 3: return WorldPositionQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 4: return ArchetypeComponent.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 5: return Persistence.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 6: return ConnectedEntity.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 7: return UniqueID.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 8: return Connection.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 9: return ConnectionScene.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 10: return Global.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 11: return GlobalQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 12: return Tag.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 13: return TagQuery.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 14: return PreserveChildren.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 15: return Scene.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 16: return AssetId.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 17: return GenericScale.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 18: return _7304d3ec37e2d4c06851177c45cddcac_4038695098842026948.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 19: return _a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 20: return _a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 21: return _a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 22: return _a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 23: return _a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 24: return _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 25: return _ae3c067ae8cdc3a188cd2fc9e5c1f40c_15434348239100244971.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 26: return _c865ca334c7504582b74c7f34f9efe3d_3701823384564508663.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 27: return _dc51daba6bd26400abb19c32e4b4b945_2336683391229707251.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 28: return _dc51daba6bd26400abb19c32e4b4b945_3856456226331623987.FromInterop(data, dataSize, simFrames, simFramesCount);
                case 29: return _dc51daba6bd26400abb19c32e4b4b945_7239968138705979096.FromInterop(data, dataSize, simFrames, simFramesCount);
            }

            throw new ArgumentException($"Unkown component type {type}", nameof(type));
        }

        public unsafe void UpdateComponent(INativeCoreComponentUpdater updater, InteropEntity entity, ICoherenceComponentData component)
        {
            var componentType = component.GetComponentType();
            var frames = component.GetSimulationFrames();

            switch (componentType)
            {
                case 0:
                {
                    var orig = (WorldPosition)component;
                    var val = new WorldPosition.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 1:
                {
                    var orig = (WorldOrientation)component;
                    var val = new WorldOrientation.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 2:
                {
                    var orig = (LocalUserComponent)component;
                    var val = new LocalUserComponent.Interop();

                    val.localIndex = orig.localIndex;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 3:
                {
                    var orig = (WorldPositionQuery)component;
                    var val = new WorldPositionQuery.Interop();

                    val.position = orig.position;
                    val.radius = orig.radius;
                    val.buffer = orig.buffer;

                    updater.UpdateComponent(entity, componentType, val, 20, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 4:
                {
                    var orig = (ArchetypeComponent)component;
                    var val = new ArchetypeComponent.Interop();

                    val.index = orig.index;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 5:
                {
                    var orig = (Persistence)component;
                    var val = new Persistence.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 6:
                {
                    var orig = (ConnectedEntity)component;
                    var val = new ConnectedEntity.Interop();

                    val.value = orig.value;
                    val.pos = orig.pos;
                    val.rot = orig.rot;
                    val.scale = orig.scale;

                    updater.UpdateComponent(entity, componentType, val, 44, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 7:
                {
                    var orig = (UniqueID)component;
                    var val = new UniqueID.Interop();

                    var pinneduuid = orig.uuid != null ? Encoding.UTF8.GetBytes(orig.uuid) : null; fixed (void* pinnedPtruuid = pinneduuid) { val.uuid = new ByteArray { Data = pinnedPtruuid, Length =  pinneduuid?.Length ?? 0 };

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 8:
                {
                    var orig = (Connection)component;
                    var val = new Connection.Interop();

                    val.id = orig.id;
                    val.type = orig.type;

                    updater.UpdateComponent(entity, componentType, val, 8, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 9:
                {
                    var orig = (ConnectionScene)component;
                    var val = new ConnectionScene.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 10:
                {
                    var orig = (Global)component;
                    var val = new Global.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 11:
                {
                    var orig = (GlobalQuery)component;
                    var val = new GlobalQuery.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 12:
                {
                    var orig = (Tag)component;
                    var val = new Tag.Interop();

                    var pinnedtag = orig.tag != null ? Encoding.UTF8.GetBytes(orig.tag) : null; fixed (void* pinnedPtrtag = pinnedtag) { val.tag = new ByteArray { Data = pinnedPtrtag, Length =  pinnedtag?.Length ?? 0 };

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 13:
                {
                    var orig = (TagQuery)component;
                    var val = new TagQuery.Interop();

                    var pinnedtag = orig.tag != null ? Encoding.UTF8.GetBytes(orig.tag) : null; fixed (void* pinnedPtrtag = pinnedtag) { val.tag = new ByteArray { Data = pinnedPtrtag, Length =  pinnedtag?.Length ?? 0 };

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 14:
                {
                    var orig = (PreserveChildren)component;
                    var val = new PreserveChildren.Interop();


                    updater.UpdateComponent(entity, componentType, val, 0, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 15:
                {
                    var orig = (Scene)component;
                    var val = new Scene.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 16:
                {
                    var orig = (AssetId)component;
                    var val = new AssetId.Interop();

                    val.value = orig.value;
                    val.isFromGroup = orig.isFromGroup ? (System.Byte)1 : (System.Byte)0;

                    updater.UpdateComponent(entity, componentType, val, 5, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 17:
                {
                    var orig = (GenericScale)component;
                    var val = new GenericScale.Interop();

                    val.value = orig.value;

                    updater.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 18:
                {
                    var orig = (_7304d3ec37e2d4c06851177c45cddcac_4038695098842026948)component;
                    var val = new _7304d3ec37e2d4c06851177c45cddcac_4038695098842026948.Interop();

                    val.linearVelocity = orig.linearVelocity;

                    updater.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 19:
                {
                    var orig = (_a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348)component;
                    var val = new _a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348.Interop();

                    var pinnedauthPublicKey = orig.authPublicKey != null ? Encoding.UTF8.GetBytes(orig.authPublicKey) : null; fixed (void* pinnedPtrauthPublicKey = pinnedauthPublicKey) { val.authPublicKey = new ByteArray { Data = pinnedPtrauthPublicKey, Length =  pinnedauthPublicKey?.Length ?? 0 };

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 20:
                {
                    var orig = (_a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177)component;
                    var val = new _a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177.Interop();

                    val.rotation = orig.rotation;

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 21:
                {
                    var orig = (_a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608)component;
                    var val = new _a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608.Interop();

                    val.holding = orig.holding;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 22:
                {
                    var orig = (_a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198)component;
                    var val = new _a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198.Interop();

                    val.hasRobotCode = orig.hasRobotCode ? (System.Byte)1 : (System.Byte)0;

                    updater.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 23:
                {
                    var orig = (_a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181)component;
                    var val = new _a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181.Interop();

                    val.rotation = orig.rotation;

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 24:
                {
                    var orig = (_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)component;
                    var val = new _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.Interop();

                    val.redScore = orig.redScore;
                    val.blueScore = orig.blueScore;
                    val.robotMode = orig.robotMode;
                    val.timeRemaining = orig.timeRemaining;

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 25:
                {
                    var orig = (_ae3c067ae8cdc3a188cd2fc9e5c1f40c_15434348239100244971)component;
                    var val = new _ae3c067ae8cdc3a188cd2fc9e5c1f40c_15434348239100244971.Interop();

                    val.linearVelocity = orig.linearVelocity;

                    updater.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 26:
                {
                    var orig = (_c865ca334c7504582b74c7f34f9efe3d_3701823384564508663)component;
                    var val = new _c865ca334c7504582b74c7f34f9efe3d_3701823384564508663.Interop();

                    val.linearVelocity = orig.linearVelocity;

                    updater.UpdateComponent(entity, componentType, val, 12, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 27:
                {
                    var orig = (_dc51daba6bd26400abb19c32e4b4b945_2336683391229707251)component;
                    var val = new _dc51daba6bd26400abb19c32e4b4b945_2336683391229707251.Interop();

                    val.hasRobotCode = orig.hasRobotCode ? (System.Byte)1 : (System.Byte)0;

                    updater.UpdateComponent(entity, componentType, val, 1, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
                case 28:
                {
                    var orig = (_dc51daba6bd26400abb19c32e4b4b945_3856456226331623987)component;
                    var val = new _dc51daba6bd26400abb19c32e4b4b945_3856456226331623987.Interop();

                    var pinnedauthPublicKey = orig.authPublicKey != null ? Encoding.UTF8.GetBytes(orig.authPublicKey) : null; fixed (void* pinnedPtrauthPublicKey = pinnedauthPublicKey) { val.authPublicKey = new ByteArray { Data = pinnedPtrauthPublicKey, Length =  pinnedauthPublicKey?.Length ?? 0 };

                    updater.UpdateComponent(entity, componentType, val, 16, component.FieldsMask, component.StoppedMask, frames);

}                    return;
                }
                case 29:
                {
                    var orig = (_dc51daba6bd26400abb19c32e4b4b945_7239968138705979096)component;
                    var val = new _dc51daba6bd26400abb19c32e4b4b945_7239968138705979096.Interop();

                    val.holding = orig.holding;

                    updater.UpdateComponent(entity, componentType, val, 4, component.FieldsMask, component.StoppedMask, frames);

                    return;
                }
            }

            throw new NotImplementedException($"Failed to update a component with type {componentType}.");
        }

        public unsafe IEntityCommand GetCommand(UInt32 type, IntPtr data, Int32 dataSize)
        {
            switch (type)
            {
                  case 0: return AuthorityRequest.FromInterop(data, dataSize);
                  case 1: return AuthorityTransfer.FromInterop(data, dataSize);
                  case 2: return QuerySynced.FromInterop(data, dataSize);
                  case 3: return AdoptOrphan.FromInterop(data, dataSize);
                  case 4: return PersistenceReady.FromInterop(data, dataSize);
                  case 5: return SceneIndexChanged.FromInterop(data, dataSize);
                  case 6: return _a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899.FromInterop(data, dataSize);
                  case 7: return _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb.FromInterop(data, dataSize);
                  case 8: return _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b.FromInterop(data, dataSize);
            }

            throw new ArgumentException($"Unkown command type {type}", nameof(type));
        }

        public unsafe IEntityInput GetInput(UInt32 type, IntPtr data, Int32 dataSize)
        {
            switch (type)
            {
                  case 0: return _a5ebc758ff4a94b588cd3a07ed28ce38.FromInterop(data, dataSize);
                  case 1: return _dc51daba6bd26400abb19c32e4b4b945.FromInterop(data, dataSize);
            }
            throw new ArgumentException($"Unknown input type {type}", nameof(type));
        }

        public unsafe bool SendCommand(INativeCoreCommandSender sender, InteropEntity entity, MessageTarget target, IEntityCommand command)
        {
            var type = command.GetComponentType();
            switch (type)
            {
                case 0:
                {
                    var orig = (AuthorityRequest)command;
                    var val = new AuthorityRequest.Interop();

                    val.requester = orig.requester;
                    val.authorityType = orig.authorityType;

                    return sender.SendCommand(entity, target, type, val, 8);

                }
                case 1:
                {
                    var orig = (AuthorityTransfer)command;
                    var val = new AuthorityTransfer.Interop();

                    val.newAuthority = orig.newAuthority;
                    val.accepted = orig.accepted ? (System.Byte)1 : (System.Byte)0;
                    val.authorityType = orig.authorityType;

                    return sender.SendCommand(entity, target, type, val, 9);

                }
                case 2:
                {
                    var orig = (QuerySynced)command;
                    var val = new QuerySynced.Interop();

                    val.liveQuerySynced = orig.liveQuerySynced ? (System.Byte)1 : (System.Byte)0;
                    val.globalQuerySynced = orig.globalQuerySynced ? (System.Byte)1 : (System.Byte)0;

                    return sender.SendCommand(entity, target, type, val, 2);

                }
                case 3:
                {
                    var orig = (AdoptOrphan)command;
                    var val = new AdoptOrphan.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 4:
                {
                    var orig = (PersistenceReady)command;
                    var val = new PersistenceReady.Interop();


                    return sender.SendCommand(entity, target, type, val, 0);

                }
                case 5:
                {
                    var orig = (SceneIndexChanged)command;
                    var val = new SceneIndexChanged.Interop();

                    val.sceneIndex = orig.sceneIndex;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 6:
                {
                    var orig = (_a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899)command;
                    var val = new _a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899.Interop();

                    var pinnedprivateKeyChallenge = orig.privateKeyChallenge != null ? Encoding.UTF8.GetBytes(orig.privateKeyChallenge) : null; fixed (void* pinnedPtrprivateKeyChallenge = pinnedprivateKeyChallenge) { val.privateKeyChallenge = new ByteArray { Data = pinnedPtrprivateKeyChallenge, Length =  pinnedprivateKeyChallenge?.Length ?? 0 };

                    return sender.SendCommand(entity, target, type, val, 16);

}                }
                case 7:
                {
                    var orig = (_a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb)command;
                    var val = new _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb.Interop();

                    val.mode = orig.mode;

                    return sender.SendCommand(entity, target, type, val, 4);

                }
                case 8:
                {
                    var orig = (_dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b)command;
                    var val = new _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b.Interop();

                    var pinnedprivateKeyChallenge = orig.privateKeyChallenge != null ? Encoding.UTF8.GetBytes(orig.privateKeyChallenge) : null; fixed (void* pinnedPtrprivateKeyChallenge = pinnedprivateKeyChallenge) { val.privateKeyChallenge = new ByteArray { Data = pinnedPtrprivateKeyChallenge, Length =  pinnedprivateKeyChallenge?.Length ?? 0 };

                    return sender.SendCommand(entity, target, type, val, 16);

}                }
            }

            throw new NotImplementedException($"Failed to send a command with type {type}.");
        }

        public unsafe void SendInput(INativeCoreInputSender sender, InteropEntity entity, long frame, IEntityInput input)
        {
            var type = input.GetComponentType();
            var inputData = (InputData)input;
            switch (type)
            {
                case 0:
                {
                    var orig = (_a5ebc758ff4a94b588cd3a07ed28ce38)inputData.Input;
                    var val = new _a5ebc758ff4a94b588cd3a07ed28ce38.Interop();


                    sender.SendInput(entity, frame, type, val, 0);

                    return;
                }
                case 1:
                {
                    var orig = (_dc51daba6bd26400abb19c32e4b4b945)inputData.Input;
                    var val = new _dc51daba6bd26400abb19c32e4b4b945.Interop();

                    val.j0a0 = orig.j0a0;
                    val.j0a1 = orig.j0a1;
                    val.j0a2 = orig.j0a2;
                    val.j0a3 = orig.j0a3;
                    val.j0a4 = orig.j0a4;
                    val.j0a5 = orig.j0a5;
                    val.j1a0 = orig.j1a0;
                    val.j1a1 = orig.j1a1;
                    val.j1a2 = orig.j1a2;
                    val.j1a3 = orig.j1a3;
                    val.j1a4 = orig.j1a4;
                    val.j1a5 = orig.j1a5;
                    val.j2a0 = orig.j2a0;
                    val.j2a1 = orig.j2a1;
                    val.j2a2 = orig.j2a2;
                    val.j2a3 = orig.j2a3;
                    val.j2a4 = orig.j2a4;
                    val.j2a5 = orig.j2a5;
                    val.j3a0 = orig.j3a0;
                    val.j3a1 = orig.j3a1;
                    val.j3a2 = orig.j3a2;
                    val.j3a3 = orig.j3a3;
                    val.j3a4 = orig.j3a4;
                    val.j3a5 = orig.j3a5;
                    val.j0b0 = orig.j0b0 ? (System.Byte)1 : (System.Byte)0;
                    val.j0b1 = orig.j0b1 ? (System.Byte)1 : (System.Byte)0;
                    val.j0b2 = orig.j0b2 ? (System.Byte)1 : (System.Byte)0;
                    val.j0b3 = orig.j0b3 ? (System.Byte)1 : (System.Byte)0;
                    val.j0b4 = orig.j0b4 ? (System.Byte)1 : (System.Byte)0;
                    val.j0b5 = orig.j0b5 ? (System.Byte)1 : (System.Byte)0;
                    val.j0b6 = orig.j0b6 ? (System.Byte)1 : (System.Byte)0;
                    val.j0b7 = orig.j0b7 ? (System.Byte)1 : (System.Byte)0;
                    val.j0b8 = orig.j0b8 ? (System.Byte)1 : (System.Byte)0;
                    val.j0b9 = orig.j0b9 ? (System.Byte)1 : (System.Byte)0;
                    val.j0b10 = orig.j0b10 ? (System.Byte)1 : (System.Byte)0;
                    val.j0b11 = orig.j0b11 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b0 = orig.j1b0 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b1 = orig.j1b1 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b2 = orig.j1b2 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b3 = orig.j1b3 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b4 = orig.j1b4 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b5 = orig.j1b5 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b6 = orig.j1b6 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b7 = orig.j1b7 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b8 = orig.j1b8 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b9 = orig.j1b9 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b10 = orig.j1b10 ? (System.Byte)1 : (System.Byte)0;
                    val.j1b11 = orig.j1b11 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b0 = orig.j2b0 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b1 = orig.j2b1 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b2 = orig.j2b2 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b3 = orig.j2b3 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b4 = orig.j2b4 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b5 = orig.j2b5 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b6 = orig.j2b6 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b7 = orig.j2b7 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b8 = orig.j2b8 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b9 = orig.j2b9 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b10 = orig.j2b10 ? (System.Byte)1 : (System.Byte)0;
                    val.j2b11 = orig.j2b11 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b0 = orig.j3b0 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b1 = orig.j3b1 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b2 = orig.j3b2 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b3 = orig.j3b3 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b4 = orig.j3b4 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b5 = orig.j3b5 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b6 = orig.j3b6 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b7 = orig.j3b7 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b8 = orig.j3b8 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b9 = orig.j3b9 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b10 = orig.j3b10 ? (System.Byte)1 : (System.Byte)0;
                    val.j3b11 = orig.j3b11 ? (System.Byte)1 : (System.Byte)0;

                    sender.SendInput(entity, frame, type, val, 144);

                    return;
                }
            }

            throw new NotImplementedException($"Failed to send an input with type {type}.");
        }
    }

}
