// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_a9502fe73cf514f0296d05af4c2fb75f_08d8f10ffed34f3e86e65928a8068dd4 : PositionBinding
    {   
        private global::UnityEngine.RectTransform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.RectTransform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a9502fe73cf514f0296d05af4c2fb75f_4f99f34dfe204382b2796d836bce3d9e : IntBinding
    {   
        private global::GameGUI CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::GameGUI)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701);
        public override string CoherenceComponentName => "_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.redScore); }
            set { CastedUnityComponent.redScore = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent).redScore;

            var simFrame = ((_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent).redScoreSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.redScore = Value;
            }
            else
            {
                update.redScore = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.redScoreSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a9502fe73cf514f0296d05af4c2fb75f_c69d16f1fbfc44cc833fff2cb9178531 : IntBinding
    {   
        private global::GameGUI CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::GameGUI)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701);
        public override string CoherenceComponentName => "_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.blueScore); }
            set { CastedUnityComponent.blueScore = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent).blueScore;

            var simFrame = ((_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent).blueScoreSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.blueScore = Value;
            }
            else
            {
                update.blueScore = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.blueScoreSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a9502fe73cf514f0296d05af4c2fb75f_ebbb6d25a3c245d4a2e6eebbe7d675b7 : EnumBinding
    {   
        private global::GameGUI CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::GameGUI)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701);
        public override string CoherenceComponentName => "_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Int32 Value
        {
            get { return (System.Int32)CastedUnityComponent.robotMode; }
            set { CastedUnityComponent.robotMode = (RobotMode)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent).robotMode;

            var simFrame = ((_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent).robotModeSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.robotMode = Value;
            }
            else
            {
                update.robotMode = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.robotModeSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a9502fe73cf514f0296d05af4c2fb75f_fc629d4485cc425e9e03101b6f9d6581 : FloatBinding
    {   
        private global::GameGUI CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::GameGUI)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701);
        public override string CoherenceComponentName => "_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701";
        public override uint FieldMask => 0b00000000000000000000000000001000;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.timeRemaining); }
            set { CastedUnityComponent.timeRemaining = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent).timeRemaining;

            var simFrame = ((_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent).timeRemainingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.timeRemaining = Value;
            }
            else
            {
                update.timeRemaining = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.timeRemainingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_a9502fe73cf514f0296d05af4c2fb75f : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_a9502fe73cf514f0296d05af4c2fb75f>();
        
        private global::GameGUI _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["08d8f10ffed34f3e86e65928a8068dd4"] = new Binding_a9502fe73cf514f0296d05af4c2fb75f_08d8f10ffed34f3e86e65928a8068dd4(),
			["4f99f34dfe204382b2796d836bce3d9e"] = new Binding_a9502fe73cf514f0296d05af4c2fb75f_4f99f34dfe204382b2796d836bce3d9e(),
			["c69d16f1fbfc44cc833fff2cb9178531"] = new Binding_a9502fe73cf514f0296d05af4c2fb75f_c69d16f1fbfc44cc833fff2cb9178531(),
			["ebbb6d25a3c245d4a2e6eebbe7d675b7"] = new Binding_a9502fe73cf514f0296d05af4c2fb75f_ebbb6d25a3c245d4a2e6eebbe7d675b7(),
			["fc629d4485cc425e9e03101b6f9d6581"] = new Binding_a9502fe73cf514f0296d05af4c2fb75f_fc629d4485cc425e9e03101b6f9d6581(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_a9502fe73cf514f0296d05af4c2fb75f()
        {
            bakedCommandBindings.Add("0956f6f92f2040518555e67a100622eb", BakeCommandBinding__a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb_CommandTarget = (global::GameGUI)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"GameGUI.CmdSetRobotMode",
            	"(RobotMode)",
            	SendCommand__a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb,
            	ReceiveLocalCommand__a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb,
            	MessageTarget.All,
            	_a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb(GenericCommandRequestArgs requestArgs)
        {
            var command = new _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.mode = (System.Int32)(int)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb(GenericCommandRequestArgs requestArgs)
        {
            var command = new _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.mode = (System.Int32)(int)requestArgs.Args[0];

            ReceiveCommand__a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb(command);
        }

        private void ReceiveCommand__a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb(_a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb command)
        {
            var target = _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb_CommandTarget;
			target.CmdSetRobotMode((RobotMode)(command.mode));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb castedCommand:
                    ReceiveCommand__a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_a9502fe73cf514f0296d05af4c2fb75f Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_a9502fe73cf514f0296d05af4c2fb75f>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
