// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_a5ebc758ff4a94b588cd3a07ed28ce38_b3737516ea8f4d89a5959715d41e9468 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a5ebc758ff4a94b588cd3a07ed28ce38_62315d1f955f44a589f0bd9d15a8b5c6 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a5ebc758ff4a94b588cd3a07ed28ce38_8b004d07bcf747179bbc2e9d1bfb630a : StringBinding
    {   
        private global::RobotController CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::RobotController)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348);
        public override string CoherenceComponentName => "_a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.authPublicKey); }
            set { CastedUnityComponent.authPublicKey = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348)coherenceComponent).authPublicKey;

            var simFrame = ((_a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348)coherenceComponent).authPublicKeySimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.authPublicKey = Value;
            }
            else
            {
                update.authPublicKey = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.authPublicKeySimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a5ebc758ff4a94b588cd3a07ed28ce38_b9363dbd3311456098996524149466a9 : BoolBinding
    {   
        private global::CodeConnector CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::CodeConnector)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198);
        public override string CoherenceComponentName => "_a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.hasRobotCode); }
            set { CastedUnityComponent.hasRobotCode = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198)coherenceComponent).hasRobotCode;

            var simFrame = ((_a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198)coherenceComponent).hasRobotCodeSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.hasRobotCode = Value;
            }
            else
            {
                update.hasRobotCode = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.hasRobotCodeSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a5ebc758ff4a94b588cd3a07ed28ce38_2974e341d5d847809be117dfd32c4d25 : IntBinding
    {   
        private global::BallStorage CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::BallStorage)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608);
        public override string CoherenceComponentName => "_a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.holding); }
            set { CastedUnityComponent.holding = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608)coherenceComponent).holding;

            var simFrame = ((_a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608)coherenceComponent).holdingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.holding = Value;
            }
            else
            {
                update.holding = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.holdingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a5ebc758ff4a94b588cd3a07ed28ce38_fb154ba947104a08b050ed6e0d4fa3af : DeepRotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177);
        public override string CoherenceComponentName => "_a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(CastedUnityComponent.localRotation); }
            set { CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177)coherenceComponent).rotation;

            var simFrame = ((_a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177)coherenceComponent).rotationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.rotation = Value;
            }
            else
            {
                update.rotation = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.rotationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_a5ebc758ff4a94b588cd3a07ed28ce38_a6c17a4938f949e1a8d1e93ef29a30fd : DeepRotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181);
        public override string CoherenceComponentName => "_a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(CastedUnityComponent.localRotation); }
            set { CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181)coherenceComponent).rotation;

            var simFrame = ((_a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181)coherenceComponent).rotationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.rotation = Value;
            }
            else
            {
                update.rotation = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.rotationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_a5ebc758ff4a94b588cd3a07ed28ce38 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_a5ebc758ff4a94b588cd3a07ed28ce38>();
        
        private global::RobotController _a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899_CommandTarget;
        
        private InputBuffer<_a5ebc758ff4a94b588cd3a07ed28ce38> inputBuffer;
        private _a5ebc758ff4a94b588cd3a07ed28ce38 currentInput;
        private long lastAddedFrame = -1;
        private CoherenceInput coherenceInput;
        private long currentSimulationFrame => coherenceInput.CurrentSimulationFrame;
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["b3737516ea8f4d89a5959715d41e9468"] = new Binding_a5ebc758ff4a94b588cd3a07ed28ce38_b3737516ea8f4d89a5959715d41e9468(),
			["62315d1f955f44a589f0bd9d15a8b5c6"] = new Binding_a5ebc758ff4a94b588cd3a07ed28ce38_62315d1f955f44a589f0bd9d15a8b5c6(),
			["8b004d07bcf747179bbc2e9d1bfb630a"] = new Binding_a5ebc758ff4a94b588cd3a07ed28ce38_8b004d07bcf747179bbc2e9d1bfb630a(),
			["b9363dbd3311456098996524149466a9"] = new Binding_a5ebc758ff4a94b588cd3a07ed28ce38_b9363dbd3311456098996524149466a9(),
			["2974e341d5d847809be117dfd32c4d25"] = new Binding_a5ebc758ff4a94b588cd3a07ed28ce38_2974e341d5d847809be117dfd32c4d25(),
			["fb154ba947104a08b050ed6e0d4fa3af"] = new Binding_a5ebc758ff4a94b588cd3a07ed28ce38_fb154ba947104a08b050ed6e0d4fa3af(),
			["a6c17a4938f949e1a8d1e93ef29a30fd"] = new Binding_a5ebc758ff4a94b588cd3a07ed28ce38_a6c17a4938f949e1a8d1e93ef29a30fd(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_a5ebc758ff4a94b588cd3a07ed28ce38()
        {
            bakedCommandBindings.Add("02db61c1968e44fc901f2b45ab369899", BakeCommandBinding__a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899_CommandTarget = (global::RobotController)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"RobotController.CmdSetInputClient",
            	"(System.String)",
            	SendCommand__a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899,
            	ReceiveLocalCommand__a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899,
            	MessageTarget.All,
            	_a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899(GenericCommandRequestArgs requestArgs)
        {
            var command = new _a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.privateKeyChallenge = (System.String)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899(GenericCommandRequestArgs requestArgs)
        {
            var command = new _a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.privateKeyChallenge = (System.String)requestArgs.Args[0];

            ReceiveCommand__a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899(command);
        }

        private void ReceiveCommand__a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899(_a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899 command)
        {
            var target = _a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899_CommandTarget;
			target.CmdSetInputClient((System.String)(command.privateKeyChallenge));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899 castedCommand:
                    ReceiveCommand__a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_a5ebc758ff4a94b588cd3a07ed28ce38 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
            if (bridge != null)
            {
                bridge.OnLateFixedNetworkUpdate -= SendInputState;
            }
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_a5ebc758ff4a94b588cd3a07ed28ce38>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
            coherenceInput = input;
            inputBuffer = new InputBuffer<_a5ebc758ff4a94b588cd3a07ed28ce38>(coherenceInput.InitialBufferSize, coherenceInput.InitialInputDelay, coherenceInput.UseFixedSimulationFrames);
            
            coherenceInput.internalSetButton = SetButton;
            coherenceInput.internalSetAxis = SetAxis;
            coherenceInput.internalSetAxis2D = SetAxis2D;
            coherenceInput.internalSetAxis3D = SetAxis3D;
            coherenceInput.internalSetRotation = SetRotation;
            coherenceInput.internalSetInteger = SetInteger;
            coherenceInput.internalSetString = SetString;
            coherenceInput.internalGetButton = GetButton;
            coherenceInput.internalGetAxis = GetAxis;
            coherenceInput.internalGetAxis2D = GetAxis2D;
            coherenceInput.internalGetAxis3D = GetAxis3D;
            coherenceInput.internalGetRotation = GetRotation;
            coherenceInput.internalGetInteger = GetInteger;
            coherenceInput.internalGetString = GetString;
            coherenceInput.internalRequestBuffer = () => inputBuffer;
            coherenceInput.internalOnInputReceived += OnInput;
            
            if (coherenceInput.UseFixedSimulationFrames)
            {
                bridge.OnLateFixedNetworkUpdate += SendInputState;
            }
        }

        private void SetButton(string name, bool value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input button of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis(string name, float value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis2D(string name, Vector2 value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis2D of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis3D(string name, Vector3 value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis3D of name: {name}.");
                    break;
            }
        }
        
        private void SetRotation(string name, Quaternion value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input rotation of name: {name}.");
                    break;
            }
        }
        
        private void SetInteger(string name, int value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
        }
        
        private void SetString(string name, string value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input string of name: {name}.");
                    break;
            }
        }
        
        public override void SendInputState()
        {
            if (!coherenceInput.IsProducer || !coherenceInput.IsReadyToProcessInputs || !coherenceInput.IsInputOwner)
            {
                return;
            }

            if (lastAddedFrame != currentSimulationFrame)
            {
                inputBuffer.AddInput(currentInput, currentSimulationFrame);
                lastAddedFrame = currentSimulationFrame;
            }

            while (inputBuffer.DequeueForSending(currentSimulationFrame, out long frameToSend, out _a5ebc758ff4a94b588cd3a07ed28ce38 input, out bool differs))
            {
                coherenceInput.DebugOnInputSent(frameToSend, input);
                client.SendInput(input, frameToSend, entityId);
            }
        }
        
        private bool ShouldPollCurrentInput(long frame)
        {
            return coherenceInput.IsProducer && coherenceInput.Delay == 0 && frame == currentSimulationFrame;
        }
        
        private bool GetButton(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _a5ebc758ff4a94b588cd3a07ed28ce38 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input button of name: {name}.");
                    break;
            }
            
            return default;
        }
        
        private float GetAxis(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _a5ebc758ff4a94b588cd3a07ed28ce38 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis of name: {name}.");
                    break;
            }
            
            return default;
        }
        
        private Vector2 GetAxis2D(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _a5ebc758ff4a94b588cd3a07ed28ce38 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis2D of name: {name}.");
                    break;
            }
            
            return Vector2.zero;
        }
        
        private Vector3 GetAxis3D(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _a5ebc758ff4a94b588cd3a07ed28ce38 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis3D of name: {name}.");
                    break;
            }
            
            return Vector3.zero;
        }
        
        private Quaternion GetRotation(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _a5ebc758ff4a94b588cd3a07ed28ce38 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input rotation of name: {name}.");
                    break;
            }
            
            return Quaternion.identity;
        }
        
        private int GetInteger(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _a5ebc758ff4a94b588cd3a07ed28ce38 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
            
            return 0;
        }
        
        private string GetString(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _a5ebc758ff4a94b588cd3a07ed28ce38 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
            
            return null;
        }
        
        private void OnInput(IEntityInput entityInput)
        {
            var input = (_a5ebc758ff4a94b588cd3a07ed28ce38)entityInput;
            coherenceInput.DebugOnInputReceived(entityInput.Frame, entityInput);
            inputBuffer.ReceiveInput(input, entityInput.Frame);
        }
    }
}
