// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_dc51daba6bd26400abb19c32e4b4b945_fc2010f160904236b7832fea7ffd6618 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_dc51daba6bd26400abb19c32e4b4b945_50692f1e65ff4037aae1e95fd249edfc : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_dc51daba6bd26400abb19c32e4b4b945_29e038ee24774b9ea0839d212be55997 : StringBinding
    {   
        private global::RobotController CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::RobotController)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dc51daba6bd26400abb19c32e4b4b945_3856456226331623987);
        public override string CoherenceComponentName => "_dc51daba6bd26400abb19c32e4b4b945_3856456226331623987";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.authPublicKey); }
            set { CastedUnityComponent.authPublicKey = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dc51daba6bd26400abb19c32e4b4b945_3856456226331623987)coherenceComponent).authPublicKey;

            var simFrame = ((_dc51daba6bd26400abb19c32e4b4b945_3856456226331623987)coherenceComponent).authPublicKeySimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dc51daba6bd26400abb19c32e4b4b945_3856456226331623987)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.authPublicKey = Value;
            }
            else
            {
                update.authPublicKey = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.authPublicKeySimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dc51daba6bd26400abb19c32e4b4b945_3856456226331623987();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_dc51daba6bd26400abb19c32e4b4b945_f9fc6594bf06423886e84c6867eea740 : BoolBinding
    {   
        private global::CodeConnector CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::CodeConnector)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dc51daba6bd26400abb19c32e4b4b945_2336683391229707251);
        public override string CoherenceComponentName => "_dc51daba6bd26400abb19c32e4b4b945_2336683391229707251";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.hasRobotCode); }
            set { CastedUnityComponent.hasRobotCode = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dc51daba6bd26400abb19c32e4b4b945_2336683391229707251)coherenceComponent).hasRobotCode;

            var simFrame = ((_dc51daba6bd26400abb19c32e4b4b945_2336683391229707251)coherenceComponent).hasRobotCodeSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dc51daba6bd26400abb19c32e4b4b945_2336683391229707251)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.hasRobotCode = Value;
            }
            else
            {
                update.hasRobotCode = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.hasRobotCodeSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dc51daba6bd26400abb19c32e4b4b945_2336683391229707251();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_dc51daba6bd26400abb19c32e4b4b945_50e44879de3248beb8e0e474a970956c : IntBinding
    {   
        private global::BallStorage CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::BallStorage)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dc51daba6bd26400abb19c32e4b4b945_7239968138705979096);
        public override string CoherenceComponentName => "_dc51daba6bd26400abb19c32e4b4b945_7239968138705979096";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.holding); }
            set { CastedUnityComponent.holding = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dc51daba6bd26400abb19c32e4b4b945_7239968138705979096)coherenceComponent).holding;

            var simFrame = ((_dc51daba6bd26400abb19c32e4b4b945_7239968138705979096)coherenceComponent).holdingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dc51daba6bd26400abb19c32e4b4b945_7239968138705979096)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.holding = Value;
            }
            else
            {
                update.holding = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.holdingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dc51daba6bd26400abb19c32e4b4b945_7239968138705979096();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_dc51daba6bd26400abb19c32e4b4b945 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_dc51daba6bd26400abb19c32e4b4b945>();
        
        private global::RobotController _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b_CommandTarget;
        
        private InputBuffer<_dc51daba6bd26400abb19c32e4b4b945> inputBuffer;
        private _dc51daba6bd26400abb19c32e4b4b945 currentInput;
        private long lastAddedFrame = -1;
        private CoherenceInput coherenceInput;
        private long currentSimulationFrame => coherenceInput.CurrentSimulationFrame;
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["fc2010f160904236b7832fea7ffd6618"] = new Binding_dc51daba6bd26400abb19c32e4b4b945_fc2010f160904236b7832fea7ffd6618(),
			["50692f1e65ff4037aae1e95fd249edfc"] = new Binding_dc51daba6bd26400abb19c32e4b4b945_50692f1e65ff4037aae1e95fd249edfc(),
			["29e038ee24774b9ea0839d212be55997"] = new Binding_dc51daba6bd26400abb19c32e4b4b945_29e038ee24774b9ea0839d212be55997(),
			["f9fc6594bf06423886e84c6867eea740"] = new Binding_dc51daba6bd26400abb19c32e4b4b945_f9fc6594bf06423886e84c6867eea740(),
			["50e44879de3248beb8e0e474a970956c"] = new Binding_dc51daba6bd26400abb19c32e4b4b945_50e44879de3248beb8e0e474a970956c(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_dc51daba6bd26400abb19c32e4b4b945()
        {
            bakedCommandBindings.Add("52c78f213d994e45b20ae0de53e3020b", BakeCommandBinding__dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b_CommandTarget = (global::RobotController)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"RobotController.CmdSetInputClient",
            	"(System.String)",
            	SendCommand__dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b,
            	ReceiveLocalCommand__dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b,
            	MessageTarget.All,
            	_dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.privateKeyChallenge = (System.String)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.privateKeyChallenge = (System.String)requestArgs.Args[0];

            ReceiveCommand__dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b(command);
        }

        private void ReceiveCommand__dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b(_dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b command)
        {
            var target = _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b_CommandTarget;
			target.CmdSetInputClient((System.String)(command.privateKeyChallenge));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b castedCommand:
                    ReceiveCommand__dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_dc51daba6bd26400abb19c32e4b4b945 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
            if (bridge != null)
            {
                bridge.OnLateFixedNetworkUpdate -= SendInputState;
            }
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_dc51daba6bd26400abb19c32e4b4b945>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
            coherenceInput = input;
            inputBuffer = new InputBuffer<_dc51daba6bd26400abb19c32e4b4b945>(coherenceInput.InitialBufferSize, coherenceInput.InitialInputDelay, coherenceInput.UseFixedSimulationFrames);
            
            coherenceInput.internalSetButton = SetButton;
            coherenceInput.internalSetAxis = SetAxis;
            coherenceInput.internalSetAxis2D = SetAxis2D;
            coherenceInput.internalSetAxis3D = SetAxis3D;
            coherenceInput.internalSetRotation = SetRotation;
            coherenceInput.internalSetInteger = SetInteger;
            coherenceInput.internalSetString = SetString;
            coherenceInput.internalGetButton = GetButton;
            coherenceInput.internalGetAxis = GetAxis;
            coherenceInput.internalGetAxis2D = GetAxis2D;
            coherenceInput.internalGetAxis3D = GetAxis3D;
            coherenceInput.internalGetRotation = GetRotation;
            coherenceInput.internalGetInteger = GetInteger;
            coherenceInput.internalGetString = GetString;
            coherenceInput.internalRequestBuffer = () => inputBuffer;
            coherenceInput.internalOnInputReceived += OnInput;
            
            if (coherenceInput.UseFixedSimulationFrames)
            {
                bridge.OnLateFixedNetworkUpdate += SendInputState;
            }
        }

        private void SetButton(string name, bool value)
        {
            switch (name)
            {
                case "j0b0":
                    currentInput.j0b0 = value;
                    break;
                case "j0b1":
                    currentInput.j0b1 = value;
                    break;
                case "j0b2":
                    currentInput.j0b2 = value;
                    break;
                case "j0b3":
                    currentInput.j0b3 = value;
                    break;
                case "j0b4":
                    currentInput.j0b4 = value;
                    break;
                case "j0b5":
                    currentInput.j0b5 = value;
                    break;
                case "j0b6":
                    currentInput.j0b6 = value;
                    break;
                case "j0b7":
                    currentInput.j0b7 = value;
                    break;
                case "j0b8":
                    currentInput.j0b8 = value;
                    break;
                case "j0b9":
                    currentInput.j0b9 = value;
                    break;
                case "j0b10":
                    currentInput.j0b10 = value;
                    break;
                case "j0b11":
                    currentInput.j0b11 = value;
                    break;
                case "j1b0":
                    currentInput.j1b0 = value;
                    break;
                case "j1b1":
                    currentInput.j1b1 = value;
                    break;
                case "j1b2":
                    currentInput.j1b2 = value;
                    break;
                case "j1b3":
                    currentInput.j1b3 = value;
                    break;
                case "j1b4":
                    currentInput.j1b4 = value;
                    break;
                case "j1b5":
                    currentInput.j1b5 = value;
                    break;
                case "j1b6":
                    currentInput.j1b6 = value;
                    break;
                case "j1b7":
                    currentInput.j1b7 = value;
                    break;
                case "j1b8":
                    currentInput.j1b8 = value;
                    break;
                case "j1b9":
                    currentInput.j1b9 = value;
                    break;
                case "j1b10":
                    currentInput.j1b10 = value;
                    break;
                case "j1b11":
                    currentInput.j1b11 = value;
                    break;
                case "j2b0":
                    currentInput.j2b0 = value;
                    break;
                case "j2b1":
                    currentInput.j2b1 = value;
                    break;
                case "j2b2":
                    currentInput.j2b2 = value;
                    break;
                case "j2b3":
                    currentInput.j2b3 = value;
                    break;
                case "j2b4":
                    currentInput.j2b4 = value;
                    break;
                case "j2b5":
                    currentInput.j2b5 = value;
                    break;
                case "j2b6":
                    currentInput.j2b6 = value;
                    break;
                case "j2b7":
                    currentInput.j2b7 = value;
                    break;
                case "j2b8":
                    currentInput.j2b8 = value;
                    break;
                case "j2b9":
                    currentInput.j2b9 = value;
                    break;
                case "j2b10":
                    currentInput.j2b10 = value;
                    break;
                case "j2b11":
                    currentInput.j2b11 = value;
                    break;
                case "j3b0":
                    currentInput.j3b0 = value;
                    break;
                case "j3b1":
                    currentInput.j3b1 = value;
                    break;
                case "j3b2":
                    currentInput.j3b2 = value;
                    break;
                case "j3b3":
                    currentInput.j3b3 = value;
                    break;
                case "j3b4":
                    currentInput.j3b4 = value;
                    break;
                case "j3b5":
                    currentInput.j3b5 = value;
                    break;
                case "j3b6":
                    currentInput.j3b6 = value;
                    break;
                case "j3b7":
                    currentInput.j3b7 = value;
                    break;
                case "j3b8":
                    currentInput.j3b8 = value;
                    break;
                case "j3b9":
                    currentInput.j3b9 = value;
                    break;
                case "j3b10":
                    currentInput.j3b10 = value;
                    break;
                case "j3b11":
                    currentInput.j3b11 = value;
                    break;
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input button of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis(string name, float value)
        {
            switch (name)
            {
                case "j0a0":
                    currentInput.j0a0 = value;
                    break;
                case "j0a1":
                    currentInput.j0a1 = value;
                    break;
                case "j0a2":
                    currentInput.j0a2 = value;
                    break;
                case "j0a3":
                    currentInput.j0a3 = value;
                    break;
                case "j0a4":
                    currentInput.j0a4 = value;
                    break;
                case "j0a5":
                    currentInput.j0a5 = value;
                    break;
                case "j1a0":
                    currentInput.j1a0 = value;
                    break;
                case "j1a1":
                    currentInput.j1a1 = value;
                    break;
                case "j1a2":
                    currentInput.j1a2 = value;
                    break;
                case "j1a3":
                    currentInput.j1a3 = value;
                    break;
                case "j1a4":
                    currentInput.j1a4 = value;
                    break;
                case "j1a5":
                    currentInput.j1a5 = value;
                    break;
                case "j2a0":
                    currentInput.j2a0 = value;
                    break;
                case "j2a1":
                    currentInput.j2a1 = value;
                    break;
                case "j2a2":
                    currentInput.j2a2 = value;
                    break;
                case "j2a3":
                    currentInput.j2a3 = value;
                    break;
                case "j2a4":
                    currentInput.j2a4 = value;
                    break;
                case "j2a5":
                    currentInput.j2a5 = value;
                    break;
                case "j3a0":
                    currentInput.j3a0 = value;
                    break;
                case "j3a1":
                    currentInput.j3a1 = value;
                    break;
                case "j3a2":
                    currentInput.j3a2 = value;
                    break;
                case "j3a3":
                    currentInput.j3a3 = value;
                    break;
                case "j3a4":
                    currentInput.j3a4 = value;
                    break;
                case "j3a5":
                    currentInput.j3a5 = value;
                    break;
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis2D(string name, Vector2 value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis2D of name: {name}.");
                    break;
            }
        }
        
        private void SetAxis3D(string name, Vector3 value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis3D of name: {name}.");
                    break;
            }
        }
        
        private void SetRotation(string name, Quaternion value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input rotation of name: {name}.");
                    break;
            }
        }
        
        private void SetInteger(string name, int value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
        }
        
        private void SetString(string name, string value)
        {
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input string of name: {name}.");
                    break;
            }
        }
        
        public override void SendInputState()
        {
            if (!coherenceInput.IsProducer || !coherenceInput.IsReadyToProcessInputs || !coherenceInput.IsInputOwner)
            {
                return;
            }

            if (lastAddedFrame != currentSimulationFrame)
            {
                inputBuffer.AddInput(currentInput, currentSimulationFrame);
                lastAddedFrame = currentSimulationFrame;
            }

            while (inputBuffer.DequeueForSending(currentSimulationFrame, out long frameToSend, out _dc51daba6bd26400abb19c32e4b4b945 input, out bool differs))
            {
                coherenceInput.DebugOnInputSent(frameToSend, input);
                client.SendInput(input, frameToSend, entityId);
            }
        }
        
        private bool ShouldPollCurrentInput(long frame)
        {
            return coherenceInput.IsProducer && coherenceInput.Delay == 0 && frame == currentSimulationFrame;
        }
        
        private bool GetButton(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _dc51daba6bd26400abb19c32e4b4b945 input);
            
            switch (name)
            {
                case "j0b0":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b0;
                    }
                    return input.j0b0;
                case "j0b1":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b1;
                    }
                    return input.j0b1;
                case "j0b2":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b2;
                    }
                    return input.j0b2;
                case "j0b3":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b3;
                    }
                    return input.j0b3;
                case "j0b4":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b4;
                    }
                    return input.j0b4;
                case "j0b5":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b5;
                    }
                    return input.j0b5;
                case "j0b6":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b6;
                    }
                    return input.j0b6;
                case "j0b7":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b7;
                    }
                    return input.j0b7;
                case "j0b8":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b8;
                    }
                    return input.j0b8;
                case "j0b9":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b9;
                    }
                    return input.j0b9;
                case "j0b10":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b10;
                    }
                    return input.j0b10;
                case "j0b11":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0b11;
                    }
                    return input.j0b11;
                case "j1b0":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b0;
                    }
                    return input.j1b0;
                case "j1b1":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b1;
                    }
                    return input.j1b1;
                case "j1b2":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b2;
                    }
                    return input.j1b2;
                case "j1b3":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b3;
                    }
                    return input.j1b3;
                case "j1b4":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b4;
                    }
                    return input.j1b4;
                case "j1b5":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b5;
                    }
                    return input.j1b5;
                case "j1b6":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b6;
                    }
                    return input.j1b6;
                case "j1b7":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b7;
                    }
                    return input.j1b7;
                case "j1b8":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b8;
                    }
                    return input.j1b8;
                case "j1b9":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b9;
                    }
                    return input.j1b9;
                case "j1b10":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b10;
                    }
                    return input.j1b10;
                case "j1b11":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1b11;
                    }
                    return input.j1b11;
                case "j2b0":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b0;
                    }
                    return input.j2b0;
                case "j2b1":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b1;
                    }
                    return input.j2b1;
                case "j2b2":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b2;
                    }
                    return input.j2b2;
                case "j2b3":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b3;
                    }
                    return input.j2b3;
                case "j2b4":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b4;
                    }
                    return input.j2b4;
                case "j2b5":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b5;
                    }
                    return input.j2b5;
                case "j2b6":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b6;
                    }
                    return input.j2b6;
                case "j2b7":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b7;
                    }
                    return input.j2b7;
                case "j2b8":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b8;
                    }
                    return input.j2b8;
                case "j2b9":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b9;
                    }
                    return input.j2b9;
                case "j2b10":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b10;
                    }
                    return input.j2b10;
                case "j2b11":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2b11;
                    }
                    return input.j2b11;
                case "j3b0":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b0;
                    }
                    return input.j3b0;
                case "j3b1":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b1;
                    }
                    return input.j3b1;
                case "j3b2":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b2;
                    }
                    return input.j3b2;
                case "j3b3":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b3;
                    }
                    return input.j3b3;
                case "j3b4":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b4;
                    }
                    return input.j3b4;
                case "j3b5":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b5;
                    }
                    return input.j3b5;
                case "j3b6":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b6;
                    }
                    return input.j3b6;
                case "j3b7":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b7;
                    }
                    return input.j3b7;
                case "j3b8":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b8;
                    }
                    return input.j3b8;
                case "j3b9":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b9;
                    }
                    return input.j3b9;
                case "j3b10":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b10;
                    }
                    return input.j3b10;
                case "j3b11":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3b11;
                    }
                    return input.j3b11;
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input button of name: {name}.");
                    break;
            }
            
            return default;
        }
        
        private float GetAxis(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _dc51daba6bd26400abb19c32e4b4b945 input);
            
            switch (name)
            {
                case "j0a0":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0a0;
                    }
                    return input.j0a0;
                case "j0a1":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0a1;
                    }
                    return input.j0a1;
                case "j0a2":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0a2;
                    }
                    return input.j0a2;
                case "j0a3":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0a3;
                    }
                    return input.j0a3;
                case "j0a4":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0a4;
                    }
                    return input.j0a4;
                case "j0a5":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j0a5;
                    }
                    return input.j0a5;
                case "j1a0":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1a0;
                    }
                    return input.j1a0;
                case "j1a1":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1a1;
                    }
                    return input.j1a1;
                case "j1a2":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1a2;
                    }
                    return input.j1a2;
                case "j1a3":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1a3;
                    }
                    return input.j1a3;
                case "j1a4":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1a4;
                    }
                    return input.j1a4;
                case "j1a5":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j1a5;
                    }
                    return input.j1a5;
                case "j2a0":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2a0;
                    }
                    return input.j2a0;
                case "j2a1":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2a1;
                    }
                    return input.j2a1;
                case "j2a2":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2a2;
                    }
                    return input.j2a2;
                case "j2a3":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2a3;
                    }
                    return input.j2a3;
                case "j2a4":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2a4;
                    }
                    return input.j2a4;
                case "j2a5":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j2a5;
                    }
                    return input.j2a5;
                case "j3a0":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3a0;
                    }
                    return input.j3a0;
                case "j3a1":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3a1;
                    }
                    return input.j3a1;
                case "j3a2":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3a2;
                    }
                    return input.j3a2;
                case "j3a3":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3a3;
                    }
                    return input.j3a3;
                case "j3a4":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3a4;
                    }
                    return input.j3a4;
                case "j3a5":
                    if (ShouldPollCurrentInput(frame))
                    {
                        return currentInput.j3a5;
                    }
                    return input.j3a5;
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis of name: {name}.");
                    break;
            }
            
            return default;
        }
        
        private Vector2 GetAxis2D(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _dc51daba6bd26400abb19c32e4b4b945 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis2D of name: {name}.");
                    break;
            }
            
            return Vector2.zero;
        }
        
        private Vector3 GetAxis3D(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _dc51daba6bd26400abb19c32e4b4b945 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input axis3D of name: {name}.");
                    break;
            }
            
            return Vector3.zero;
        }
        
        private Quaternion GetRotation(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _dc51daba6bd26400abb19c32e4b4b945 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input rotation of name: {name}.");
                    break;
            }
            
            return Quaternion.identity;
        }
        
        private int GetInteger(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _dc51daba6bd26400abb19c32e4b4b945 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
            
            return 0;
        }
        
        private string GetString(string name, long? simulationFrame)
        {
            long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);
            inputBuffer.TryGetInput(frame, out _dc51daba6bd26400abb19c32e4b4b945 input);
            
            switch (name)
            {
                default:
                    logger.Error(Coherence.Log.Error.ToolkitInputMissingInput, $"No input integer of name: {name}.");
                    break;
            }
            
            return null;
        }
        
        private void OnInput(IEntityInput entityInput)
        {
            var input = (_dc51daba6bd26400abb19c32e4b4b945)entityInput;
            coherenceInput.DebugOnInputReceived(entityInput.Frame, entityInput);
            inputBuffer.ReceiveInput(input, entityInput.Frame);
        }
    }
}
