// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Connection;
    using Coherence.Entities;
    using Coherence.Serializer;
    using Coherence.Log;
    using Coherence.SimulationFrame;


    [UnityEngine.Scripting.Preserve]

    public class Definition : IDefinition
    {
        public const string schemaId = "a08583b8346518a5276478378db91e9258f7a3e9";
        public const uint InternalWorldPosition = 0;
        public const uint InternalWorldOrientation = 1;
        public const uint InternalLocalUserComponent = 2;
        public const uint InternalWorldPositionQuery = 3;
        public const uint InternalArchetypeComponent = 4;
        public const uint InternalPersistence = 5;
        public const uint InternalConnectedEntity = 6;
        public const uint InternalUniqueID = 7;
        public const uint InternalConnection = 8;
        public const uint InternalConnectionScene = 9;
        public const uint InternalGlobal = 10;
        public const uint InternalGlobalQuery = 11;
        public const uint InternalTag = 12;
        public const uint InternalTagQuery = 13;
        public const uint InternalPreserveChildren = 14;
        public const uint InternalScene = 15;
        public const uint InternalAssetId = 16;
        public const uint InternalGenericScale = 17;
        public const uint Internal_7304d3ec37e2d4c06851177c45cddcac_4038695098842026948 = 18;
        public const uint Internal_a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348 = 19;
        public const uint Internal_a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177 = 20;
        public const uint Internal_a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608 = 21;
        public const uint Internal_a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198 = 22;
        public const uint Internal_a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181 = 23;
        public const uint Internal_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701 = 24;
        public const uint Internal_ae3c067ae8cdc3a188cd2fc9e5c1f40c_15434348239100244971 = 25;
        public const uint Internal_c865ca334c7504582b74c7f34f9efe3d_3701823384564508663 = 26;
        public const uint Internal_dc51daba6bd26400abb19c32e4b4b945_2336683391229707251 = 27;
        public const uint Internal_dc51daba6bd26400abb19c32e4b4b945_3856456226331623987 = 28;
        public const uint Internal_dc51daba6bd26400abb19c32e4b4b945_7239968138705979096 = 29;
        public const uint InternalAuthorityRequest = 0;
        public const uint InternalAuthorityTransfer = 1;
        public const uint InternalQuerySynced = 2;
        public const uint InternalAdoptOrphan = 3;
        public const uint InternalPersistenceReady = 4;
        public const uint InternalSceneIndexChanged = 5;
        public const uint Internal_a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899 = 6;
        public const uint Internal_a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb = 7;
        public const uint Internal_dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b = 8;
        public const uint Internal_a5ebc758ff4a94b588cd3a07ed28ce38 = 0;
        public const uint Internal_dc51daba6bd26400abb19c32e4b4b945 = 1;

        private static readonly Dictionary<uint, string> componentNamesForTypeIds = new Dictionary<uint, string>()
        {
            { 0, "WorldPosition" },
            { 1, "WorldOrientation" },
            { 2, "LocalUserComponent" },
            { 3, "WorldPositionQuery" },
            { 4, "ArchetypeComponent" },
            { 5, "Persistence" },
            { 6, "ConnectedEntity" },
            { 7, "UniqueID" },
            { 8, "Connection" },
            { 9, "ConnectionScene" },
            { 10, "Global" },
            { 11, "GlobalQuery" },
            { 12, "Tag" },
            { 13, "TagQuery" },
            { 14, "PreserveChildren" },
            { 15, "Scene" },
            { 16, "AssetId" },
            { 17, "GenericScale" },
            { 18, "_7304d3ec37e2d4c06851177c45cddcac_4038695098842026948" },
            { 19, "_a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348" },
            { 20, "_a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177" },
            { 21, "_a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608" },
            { 22, "_a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198" },
            { 23, "_a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181" },
            { 24, "_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701" },
            { 25, "_ae3c067ae8cdc3a188cd2fc9e5c1f40c_15434348239100244971" },
            { 26, "_c865ca334c7504582b74c7f34f9efe3d_3701823384564508663" },
            { 27, "_dc51daba6bd26400abb19c32e4b4b945_2336683391229707251" },
            { 28, "_dc51daba6bd26400abb19c32e4b4b945_3856456226331623987" },
            { 29, "_dc51daba6bd26400abb19c32e4b4b945_7239968138705979096" },
        };

        public static string ComponentNameForTypeId(uint typeId)
        {
            if (componentNamesForTypeIds.TryGetValue(typeId, out string componentName))
            {
                return componentName;
            }
            else
            {
                return "";
            }
        }

        public static readonly Dictionary<uint, MessageTarget> CommandRoutingByType = new Dictionary<uint, MessageTarget>()
        {
            { Definition.InternalAuthorityRequest , MessageTarget.All },
            { Definition.InternalAuthorityTransfer , MessageTarget.All },
            { Definition.InternalQuerySynced , MessageTarget.All },
            { Definition.InternalAdoptOrphan , MessageTarget.All },
            { Definition.InternalPersistenceReady , MessageTarget.All },
            { Definition.InternalSceneIndexChanged , MessageTarget.All },
            { Definition.Internal_a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899 , MessageTarget.All },
            { Definition.Internal_a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb , MessageTarget.All },
            { Definition.Internal_dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b , MessageTarget.All },
        };

        public ICoherenceComponentData ReadComponentUpdate(uint componentType, AbsoluteSimulationFrame referenceSimulationFrame,
            IInBitStream bitStream, Logger logger)
        {
            var inProtocolStream = new InProtocolBitStream(bitStream);

            switch (componentType)
            {
                case InternalWorldPosition:
                    return WorldPosition.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldOrientation:
                    return WorldOrientation.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPersistence:
                    return Persistence.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectedEntity:
                    return ConnectedEntity.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalUniqueID:
                    return UniqueID.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnection:
                    return Connection.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectionScene:
                    return ConnectionScene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobal:
                    return Global.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobalQuery:
                    return GlobalQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTag:
                    return Tag.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTagQuery:
                    return TagQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPreserveChildren:
                    return PreserveChildren.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalScene:
                    return Scene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalAssetId:
                    return AssetId.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGenericScale:
                    return GenericScale.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_7304d3ec37e2d4c06851177c45cddcac_4038695098842026948:
                    return _7304d3ec37e2d4c06851177c45cddcac_4038695098842026948.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701:
                    return _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_ae3c067ae8cdc3a188cd2fc9e5c1f40c_15434348239100244971:
                    return _ae3c067ae8cdc3a188cd2fc9e5c1f40c_15434348239100244971.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_c865ca334c7504582b74c7f34f9efe3d_3701823384564508663:
                    return _c865ca334c7504582b74c7f34f9efe3d_3701823384564508663.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_dc51daba6bd26400abb19c32e4b4b945_2336683391229707251:
                    return _dc51daba6bd26400abb19c32e4b4b945_2336683391229707251.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_dc51daba6bd26400abb19c32e4b4b945_3856456226331623987:
                    return _dc51daba6bd26400abb19c32e4b4b945_3856456226331623987.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_dc51daba6bd26400abb19c32e4b4b945_7239968138705979096:
                    return _dc51daba6bd26400abb19c32e4b4b945_7239968138705979096.Deserialize(referenceSimulationFrame, inProtocolStream);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(componentType),
                        $"Missing serialization implementation for a component: {componentType}");
            }
        }

        public uint WriteComponentUpdate(ICoherenceComponentData data, uint serializeAs, bool isRefSimFrameValid,
            AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream protocolStream, Logger logger)
        {
            switch (serializeAs)
            {
                case InternalWorldPosition:
                    return WorldPosition.Serialize((WorldPosition)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldOrientation:
                    return WorldOrientation.Serialize((WorldOrientation)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Serialize((LocalUserComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Serialize((WorldPositionQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Serialize((ArchetypeComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPersistence:
                    return Persistence.Serialize((Persistence)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectedEntity:
                    return ConnectedEntity.Serialize((ConnectedEntity)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalUniqueID:
                    return UniqueID.Serialize((UniqueID)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnection:
                    return Connection.Serialize((Connection)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectionScene:
                    return ConnectionScene.Serialize((ConnectionScene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobal:
                    return Global.Serialize((Global)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobalQuery:
                    return GlobalQuery.Serialize((GlobalQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTag:
                    return Tag.Serialize((Tag)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTagQuery:
                    return TagQuery.Serialize((TagQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPreserveChildren:
                    return PreserveChildren.Serialize((PreserveChildren)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalScene:
                    return Scene.Serialize((Scene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalAssetId:
                    return AssetId.Serialize((AssetId)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGenericScale:
                    return GenericScale.Serialize((GenericScale)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_7304d3ec37e2d4c06851177c45cddcac_4038695098842026948:
                    return _7304d3ec37e2d4c06851177c45cddcac_4038695098842026948.Serialize((_7304d3ec37e2d4c06851177c45cddcac_4038695098842026948)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348.Serialize((_a5ebc758ff4a94b588cd3a07ed28ce38_139550269326081348)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177.Serialize((_a5ebc758ff4a94b588cd3a07ed28ce38_509211006191760177)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608.Serialize((_a5ebc758ff4a94b588cd3a07ed28ce38_5409314221323879608)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198.Serialize((_a5ebc758ff4a94b588cd3a07ed28ce38_5842616716948011198)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181.Serialize((_a5ebc758ff4a94b588cd3a07ed28ce38_7955188810710112181)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701:
                    return _a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701.Serialize((_a9502fe73cf514f0296d05af4c2fb75f_4541063488329772701)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_ae3c067ae8cdc3a188cd2fc9e5c1f40c_15434348239100244971:
                    return _ae3c067ae8cdc3a188cd2fc9e5c1f40c_15434348239100244971.Serialize((_ae3c067ae8cdc3a188cd2fc9e5c1f40c_15434348239100244971)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_c865ca334c7504582b74c7f34f9efe3d_3701823384564508663:
                    return _c865ca334c7504582b74c7f34f9efe3d_3701823384564508663.Serialize((_c865ca334c7504582b74c7f34f9efe3d_3701823384564508663)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_dc51daba6bd26400abb19c32e4b4b945_2336683391229707251:
                    return _dc51daba6bd26400abb19c32e4b4b945_2336683391229707251.Serialize((_dc51daba6bd26400abb19c32e4b4b945_2336683391229707251)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_dc51daba6bd26400abb19c32e4b4b945_3856456226331623987:
                    return _dc51daba6bd26400abb19c32e4b4b945_3856456226331623987.Serialize((_dc51daba6bd26400abb19c32e4b4b945_3856456226331623987)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_dc51daba6bd26400abb19c32e4b4b945_7239968138705979096:
                    return _dc51daba6bd26400abb19c32e4b4b945_7239968138705979096.Serialize((_dc51daba6bd26400abb19c32e4b4b945_7239968138705979096)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingComponentImplementation, ("component", data.GetComponentType()));
                    return 0;
            }
        }

        private IEntityCommand ReadCommand(uint commandType, Entity entity, MessageTarget target, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    return AuthorityRequest.Deserialize(bitStream, entity, target);
                case Definition.InternalAuthorityTransfer:
                    return AuthorityTransfer.Deserialize(bitStream, entity, target);
                case Definition.InternalQuerySynced:
                    return QuerySynced.Deserialize(bitStream, entity, target);
                case Definition.InternalAdoptOrphan:
                    return AdoptOrphan.Deserialize(bitStream, entity, target);
                case Definition.InternalPersistenceReady:
                    return PersistenceReady.Deserialize(bitStream, entity, target);
                case Definition.InternalSceneIndexChanged:
                    return SceneIndexChanged.Deserialize(bitStream, entity, target);
                case Definition.Internal_a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899.Deserialize(bitStream, entity, target);
                case Definition.Internal_a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb:
                    return _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb.Deserialize(bitStream, entity, target);
                case Definition.Internal_dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b:
                    return _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b.Deserialize(bitStream, entity, target);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(commandType),
                        $"Missing serialization implementation for a command: {commandType}");
            }
        }

        private IEntityInput ReadInput(uint inputType, Entity entity, long frame, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (inputType)
            {
                case Definition.Internal_a5ebc758ff4a94b588cd3a07ed28ce38:
                    return _a5ebc758ff4a94b588cd3a07ed28ce38.Deserialize(bitStream, entity, frame);
                case Definition.Internal_dc51daba6bd26400abb19c32e4b4b945:
                    return _dc51daba6bd26400abb19c32e4b4b945.Deserialize(bitStream, entity, frame);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(inputType),
                        $"Missing serialization implementation for an input: {inputType}");
            }
        }

        public IEntityCommand[]	ReadCommands(IInBitStream bitStream, Logger logger)
        {
            var numMessages = bitStream.ReadUint8();

            var commandData = new IEntityCommand[numMessages];

            for (var i = 0; i < numMessages; i++)
            {
            	commandData[i] = ReadCommand(bitStream, logger);
            }

            return commandData;
        }

        public IEntityInput[] ReadInputs(IInBitStream bitStream, Logger logger)
        {
            var numMessages = bitStream.ReadUint8();

            var inputData = new IEntityInput[numMessages];

            for (var i = 0; i < numMessages; i++)
            {
                var entityID = DeserializerTools.DeserializeEntity(bitStream);
                var routing = DeserializerTools.DeserializeMessageTarget(bitStream);
                var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
                var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);
                var frame = (long)bitStream.ReadUint64();
                var input = ReadInput(componentType, entityID, frame, inBitStream, logger);
                input.Routing = routing;
                inputData[i] = input;
            }

            return inputData;
        }

        public IEntityCommand ReadCommand(IInBitStream bitStream, Logger logger)
        {
            var entityID = DeserializerTools.DeserializeEntity(bitStream);
            var messageTarget = DeserializerTools.DeserializeMessageTarget(bitStream);
            var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
            var meta = DeserializerTools.DeserializeCommandMeta(bitStream);
            var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);

			var command = ReadCommand(componentType, entityID, messageTarget, inBitStream, logger);
			if (meta.HasValue)
			{
				command.UsesMeta = true;
				command.SenderClientID = new ClientID(meta.Value.SenderID);
				command.Frame = meta.Value.Frame;
			}

            return command;
        }

        public void WriteCommand(IEntityCommand data, uint commandType, IOutProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    AuthorityRequest.Serialize((AuthorityRequest)data, bitStream);
                    break;
                case Definition.InternalAuthorityTransfer:
                    AuthorityTransfer.Serialize((AuthorityTransfer)data, bitStream);
                    break;
                case Definition.InternalQuerySynced:
                    QuerySynced.Serialize((QuerySynced)data, bitStream);
                    break;
                case Definition.InternalAdoptOrphan:
                    AdoptOrphan.Serialize((AdoptOrphan)data, bitStream);
                    break;
                case Definition.InternalPersistenceReady:
                    PersistenceReady.Serialize((PersistenceReady)data, bitStream);
                    break;
                case Definition.InternalSceneIndexChanged:
                    SceneIndexChanged.Serialize((SceneIndexChanged)data, bitStream);
                    break;
                case Definition.Internal_a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899:
                    _a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899.Serialize((_a5ebc758ff4a94b588cd3a07ed28ce38_02db61c1968e44fc901f2b45ab369899)data, bitStream);
                    break;
                case Definition.Internal_a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb:
                    _a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb.Serialize((_a9502fe73cf514f0296d05af4c2fb75f_0956f6f92f2040518555e67a100622eb)data, bitStream);
                    break;
                case Definition.Internal_dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b:
                    _dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b.Serialize((_dc51daba6bd26400abb19c32e4b4b945_52c78f213d994e45b20ae0de53e3020b)data, bitStream);
                    break;
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingCommandImplementation, ("command", commandType));
                    break;
            }
        }

        public void WriteInput(IEntityInput data, uint inputType, IOutProtocolBitStream bitStream, Logger logger)
        {
            var inputData = (InputData)data;

            switch (inputType)
            {
                case Definition.Internal_a5ebc758ff4a94b588cd3a07ed28ce38:
                    _a5ebc758ff4a94b588cd3a07ed28ce38.Serialize((_a5ebc758ff4a94b588cd3a07ed28ce38)inputData.Input, bitStream);
                    break;
                case Definition.Internal_dc51daba6bd26400abb19c32e4b4b945:
                    _dc51daba6bd26400abb19c32e4b4b945.Serialize((_dc51daba6bd26400abb19c32e4b4b945)inputData.Input, bitStream);
                    break;
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingInputImplementation, ("input", inputType));
                    break;
            }
        }

        public IEntityCommand CreateAuthorityRequest(Entity entity, ClientID requester, AuthorityType authType)
        {
            return new AuthorityRequest(entity, (uint)requester, (int)authType)
			{
				Target = MessageTarget.StateAuthorityOnly,
			};
        }

        public IEntityCommand CreateAdoptOrphanCommand(Entity entity)
        {
            return new AdoptOrphan
            {
                Entity = entity,
                Target = MessageTarget.StateAuthorityOnly,
            };
        }

        public bool TryGetAuthorityRequestCommand(IEntityCommand entityCommand,
            out ClientID requester, out AuthorityType authType)
        {
            if (entityCommand is AuthorityRequest request)
            {
                requester = (ClientID)request.requester;
                authType = (AuthorityType)request.authorityType;

                return true;
            }

            requester = default;
            authType = default;

            return false;
        }

        public IEntityCommand CreateAuthorityTransfer(Entity entity, ClientID newAuthority, bool accepted, AuthorityType authType)
        {
            return new AuthorityTransfer(entity, (uint)newAuthority, accepted, (int)authType)
			{
				Target = MessageTarget.Other,
			};
        }

        public bool TryGetAuthorityTransferCommand(IEntityCommand entityCommand, out ClientID newAuthority,
            out bool transferAccepted, out AuthorityType authType)
        {
            if (entityCommand is AuthorityTransfer transfer)
            {
                newAuthority = (ClientID)transfer.newAuthority;
                transferAccepted = transfer.accepted;
                authType = (AuthorityType)transfer.authorityType;

                return true;
            }

            newAuthority = default;
            transferAccepted = default;
            authType = default;

            return false;
        }

        public ICoherenceComponentData GeneratePersistenceData()
        {
            var persistence = new Persistence();

            return persistence;
        }

        public ICoherenceComponentData GenerateCoherenceUUIDData(string uuid, AbsoluteSimulationFrame simFrame)
        {
            var uniqueID = new UniqueID();
            uniqueID.uuid = uuid;
            uniqueID.uuidSimulationFrame = simFrame;
            uniqueID.FieldsMask = 0b1;

            return uniqueID;
        }

        public ICoherenceComponentData CreateGlobalComponent()
        {
            return new Global();
        }

        public ICoherenceComponentData GenerateGlobalQueryComponent()
        {
            return new GlobalQuery();
        }

        public string ExtractCoherenceUUID(ICoherenceComponentData data)
        {
            var uniqueID = (UniqueID)data;
            return uniqueID.uuid;
        }

        public bool IsConnectedEntity(ICoherenceComponentData data)
        {
            return data.GetComponentType() == Definition.InternalConnectedEntity;
        }

        public Entity ExtractConnectedEntityID(ICoherenceComponentData data)
        {
            var connectedEntity = (ConnectedEntity)data;

            return connectedEntity.value;
        }

        public string ExtractCoherenceTag(ICoherenceComponentData data)
        {
            var tag = (Tag)data;
            return tag.tag;
        }

        public bool TryGetSceneIndexChangedCommand(IEntityCommand entityCommand, out int sceneIndex)
        {
            if (entityCommand is SceneIndexChanged changed)
            {
                sceneIndex = (int)changed.sceneIndex;

                return true;
            }

            sceneIndex = default;

            return false;
        }

        public IEntityCommand CreateSceneIndexChangedCommand(Entity entity, int sceneIndex)
        {
            return new SceneIndexChanged(entity, sceneIndex)
			{
				Target = MessageTarget.StateAuthorityOnly,
			};
        }

        public bool IsSendOrderedComponent(uint componentID)
        {
            switch(componentID)
            {
                case 6:
                    return true;
                default:
                    return false;
            }
        }
}


}
